<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GodotProjectDir>$(MSBuildProjectDirectory)\..</GodotProjectDir>
    <NoWarn>$(NoWarn);CS0436</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="GodotProjectDir" />
    <ProjectReference Include="..\MiniRPG.Runtime\MiniRPG.Runtime.csproj" />
  </ItemGroup>
</Project>
