using System;
using System.Collections.Generic;
using Godot;
using MiniRPG.Core.Config;
using MiniRPG.Core.Data;
using MiniRPG.Core.Weather;
using MiniRPG.Core.World;

namespace MiniRPG.Module.Render;

/// <summary>
/// Isometric voxel renderer: renders multi-layer block world in 2.5D isometric view.
/// Each visible block draws top face (diamond) + left side + right side.
/// Side faces are programmatically generated by sampling the bottom edges of the top tile.
/// </summary>
public partial class IsometricVoxelRenderer
{
	private const int DefaultViewDepthAbove = 4;
	private const int DefaultViewDepthBelow = 2;
	private const int DefaultCharacterSheetFrameWidth = 128;
	private const int DefaultCharacterSheetFrameHeight = 128;
	private const float LeftDarken = 0.65f;
	private const float RightDarken = 0.80f;
	private const float WallTopEdgeStrength = 0.30f;
	private static readonly IsometricLightingSettings DefaultLighting = new(
		Ambient: 1.0f,
		TopLight: 1.0f,
		LeftLight: 0.72f,
		RightLight: 0.86f,
		DepthFalloff: 0.0f,
		Contrast: 1.0f,
		ShadowStrength: 0.0f,
		OcclusionStep: 0.0f);
	private const float MinLight = 0.12f;
	private const float MaxLight = 1.65f;
	private const float SolidTopEdgeStrength = 0.22f;
	private const float NonSolidTopEdgeStrength = 0.12f;
	private const float WallSideEdgeStrength = 0.20f;
	private const float SolidSideEdgeStrength = 0.12f;
	private const float NonSolidSideEdgeStrength = 0.06f;
	private const int SideTextureWidth = VoxelFaceImageUtil.SideTextureWidth;
	private const int SideTextureHeight = VoxelFaceImageUtil.SideTextureHeight;
	private const int SideFaceHeight = VoxelFaceImageUtil.SideFaceHeight;
	private const int WallSideFaceHeight = VoxelFaceImageUtil.WallSideFaceHeight;
	private const float DefaultLeftSideDarken = LeftDarken;
	private const float DefaultRightSideDarken = RightDarken;
	private const float WallLeftSideDarken = 0.52f;
	private const float WallRightSideDarken = 0.68f;
	private const string VoxelTileRoot = "res://Assets/Art/Generated/voxel_tiles";
	private static readonly Color HoverCellTint = new(0.92f, 0.82f, 0.50f, 0.08f);
	private static readonly Color HoverCellOutlineTint = new(0.92f, 0.82f, 0.50f, 0.70f);
	private static readonly Color HoverWallTint = new(0.92f, 0.82f, 0.50f, 0.38f);
	private static readonly Vector2 HoverCellFillScale = new(1.96f, 0.98f);
	private static readonly Vector2 HoverCellOutlineScale = new(2.04f, 1.02f);

	// ── Editor X-Ray transparency ──
	private const int XRayRadius = 2;
	private const float XRayAlpha = 0.25f;
	private static readonly Color XRayOutlineTint = new(0.6f, 0.75f, 0.9f, 0.30f);
	private static readonly Vector2 XRayOutlineScale = new(2.04f, 1.02f);

	private readonly GameState _state;
	private readonly FogOfWarTracker _fogTracker;
	private readonly int _viewW;
	private readonly int _viewH;

	private Node2D? _root;
	private Camera2D? _camera;
	private SubViewportContainer? _viewportContainer;
	private SubViewport? _subViewport;
	private WeatherFxController? _weatherFxController;
	private Node2D? _combatFxWorldRoot;
	private IAnimatable? _playerAnim;

	private readonly List<Sprite2D> _spritePool = [];
	private int _spriteCount;
	private VoxelFaceBatchCanvas? _faceBatchCanvas;
	private readonly List<FaceSpriteCommand> _faceCommands = [];
	private readonly List<VoxelDrawCommand> _drawCommands = [];
	private readonly List<EntityDrawCommand> _entityCommands = [];
	private readonly List<HoverHighlightCommand> _highlightCommands = [];
	private readonly List<(Vector2 ScreenPos, long SortKey)> _xrayCells = [];
	private int _lastDrawCommandCount;
	private int _highlightCommandCount;

	private readonly Dictionary<string, CachedBlockTextures> _textureCache = new();
	private readonly Dictionary<string, Texture2D?> _voxelFaceTextureCache = new(StringComparer.OrdinalIgnoreCase);
	private IsometricLightingSettings _lighting = DefaultLighting;
	private DayNightSnapshot _dayNight = DayNightSnapshot.FullDay;
	private readonly LightMap _lightMap = new();
	private readonly TerrainAtlas _terrainAtlas = new();

	// ── Orchestration state (formerly TileMapRenderModule) ──
	private float _zoom = 1.0f;
	private float _minCameraZoom = 0.6f;
	private float _maxCameraZoom = 2.4f;
	private const float CameraZoomStep = 0.1f;
	private bool _editorViewActive;
	private int _viewCenterX;
	private int _viewCenterY;
	private int _viewCenterZ;
	private double _tileAnimationClockSeconds;
	private int _lightingProfileIndex;
	private int _tileDrawCommandCount;
	private RenderPerfSnapshot _lastPerfSnapshot = RenderPerfSnapshot.Empty;
	private double _frameTimeEwmaMs;
	private bool _hasFrameTimeEwma;
	private Vector2 _playerVisualCorrectionOffset = Vector2.Zero;
	private float _playerVisualCorrectionRemaining;
	private float _playerVisualCorrectionDuration;

	private static readonly (string Key, IsometricLightingSettings Lighting)[] LightingProfiles =
	[
		("render.lighting.profile.default", new IsometricLightingSettings(0.84f, 1.12f, 0.76f, 0.90f, 0.06f, 1.06f, 0.58f, 0.085f)),
		("render.lighting.profile.cinematic", new IsometricLightingSettings(0.72f, 1.24f, 0.62f, 0.95f, 0.09f, 1.18f, 0.76f, 0.11f)),
		("render.lighting.profile.soft", new IsometricLightingSettings(0.94f, 1.04f, 0.86f, 0.92f, 0.03f, 0.92f, 0.42f, 0.06f)),
	];

	private static readonly Dictionary<string, Color> TerrainColors = new()
	{
		[Terrains.GrassBlock] = new Color(0.3f, 0.7f, 0.2f),
		[Terrains.Grass] = new Color(0.3f, 0.7f, 0.2f),
		[Terrains.Dirt] = new Color(0.55f, 0.35f, 0.15f),
		[Terrains.Stone] = new Color(0.5f, 0.5f, 0.5f),
		[Terrains.Sand] = new Color(0.9f, 0.85f, 0.6f),
		[Terrains.Water] = new Color(0.2f, 0.4f, 0.8f, 0.7f),
		[Terrains.Mountain] = new Color(0.4f, 0.4f, 0.45f),
		[Terrains.WallStone] = new Color(0.45f, 0.45f, 0.45f),
		[Terrains.WallSoil] = new Color(0.5f, 0.3f, 0.15f),
		[Terrains.WallGranite] = new Color(0.6f, 0.55f, 0.5f),
		[Terrains.WallObsidian] = new Color(0.15f, 0.1f, 0.2f),
		[Terrains.Tree] = new Color(0.15f, 0.5f, 0.1f),
		[Terrains.Snow] = new Color(0.95f, 0.95f, 1.0f),
		[Terrains.Ice] = new Color(0.7f, 0.85f, 1.0f, 0.8f),
		[Terrains.Lava] = new Color(1.0f, 0.3f, 0.0f),
		[Terrains.Floor] = new Color(0.6f, 0.55f, 0.45f),
		[Terrains.Rubble] = new Color(0.5f, 0.45f, 0.35f),
	};

	private static readonly Dictionary<string, string> CharacterSheetMap = new(StringComparer.OrdinalIgnoreCase)
	{
		["Idle"] = "Idle",
		["Walk"] = "Walk",
		["Run"] = "Run",
		["Attack_1"] = "Attack1",
		["Attack1"] = "Attack1",
		["Pain"] = "TakeDamage",
		["TakeDamage"] = "TakeDamage",
		["Die"] = "Die",
		["Special_1"] = "Special1",
		["Special1"] = "Special1",
	};

	public IsometricVoxelRenderer(GameState state, FogOfWarTracker fogTracker, int viewW, int viewH)
	{
		_state = state;
		_fogTracker = fogTracker;
		_viewW = viewW;
		_viewH = viewH;
	}

	public int LastSpriteCount => _spriteCount;
	public int LastDrawCommandCount => _lastDrawCommandCount;
	public IsometricLightingSettings LightingSettings => _lighting;
	public Vector3I? HoverWorldCell { get; set; }
	public bool XRayEnabled { get; set; }
	public Vector3I? InspectWorldCell { get; set; }
	public Node2D CombatFxWorldRoot => _combatFxWorldRoot!;
	public bool IsIsometricMode => true;
	public int LightingProfileIndex => _lightingProfileIndex;
	public RenderPerfSnapshot LastPerfSnapshot => _lastPerfSnapshot;
	public float Zoom => _zoom;
	public bool FogMapVisible { get; set; }
	public bool MinimapVisible { get; set; }
	public Vector2I MapViewportSize => _subViewport?.Size ?? Vector2I.Zero;
	public Vector2 MapViewportContainerSize => _viewportContainer?.Size ?? Vector2.Zero;
	public bool IsRevealAll => _fogTracker.RevealAll;
	public IAnimatable? PlayerAnimatable => _playerAnim;

	public static IReadOnlyList<string> EnumerateWeatherAssetPaths() =>
		WeatherFxController.EnumerateWeatherAssetPaths();

	public void Init(
		Node2D mapRoot,
		TileSet tileSet,
		SubViewportContainer? viewportContainer,
		SubViewport? subViewport,
		Node2D? playerVisual,
		Camera2D? camera)
	{
		_viewportContainer = viewportContainer;
		_subViewport = subViewport;
		_camera = camera;

		if (playerVisual != null)
		{
			playerVisual.Visible = false;
			_playerAnim = playerVisual as IAnimatable ?? new TileAnimatable(playerVisual);
			ResAccess.RegisterAnimatable("player", _playerAnim);
			if (!string.IsNullOrWhiteSpace(_state.PlayerId))
				ResAccess.RegisterAnimatable(_state.PlayerId, _playerAnim);
		}

		var voxelRoot = new Node2D { Name = "VoxelRoot", Visible = true };
		mapRoot.AddChild(voxelRoot);
		_root = voxelRoot;

		_combatFxWorldRoot = new Node2D { Name = "CombatFxWorldRoot", ZIndex = 6 };
		mapRoot.AddChild(_combatFxWorldRoot);

		_textureCache.Clear();
		_voxelFaceTextureCache.Clear();
		_terrainAtlas.Build();

		_faceBatchCanvas?.QueueFree();
		_faceBatchCanvas = new VoxelFaceBatchCanvas
		{
			Name = "VoxelFaceBatchCanvas",
			ZIndex = 0,
		};
		_faceBatchCanvas.SetAtlasTexture(_terrainAtlas.AtlasTexture);
		_root.AddChild(_faceBatchCanvas);

		_weatherFxController = new WeatherFxController(_state);
		var weatherOverlayRoot = new Node2D { Name = "WeatherOverlayRoot", ZIndex = 1, Visible = false };
		mapRoot.AddChild(weatherOverlayRoot);
		var peripheralWeatherOverlayRoot = new Node2D { Name = "PeripheralWeatherOverlayRoot", ZIndex = 1, Visible = false };
		mapRoot.AddChild(peripheralWeatherOverlayRoot);
		var memoryWeatherOverlayRoot = new Node2D { Name = "MemoryWeatherOverlayRoot", ZIndex = 1, Visible = false };
		mapRoot.AddChild(memoryWeatherOverlayRoot);
		var weatherFxRoot = new Node2D { Name = "WeatherFxRoot", ZIndex = 2, Visible = false };
		mapRoot.AddChild(weatherFxRoot);
		var peripheralWeatherFxRoot = new Node2D { Name = "PeripheralWeatherFxRoot", ZIndex = 2, Visible = false };
		mapRoot.AddChild(peripheralWeatherFxRoot);
		_weatherFxController.Init(
			mapRoot, static _ => Vector2.Zero, new Vector2(64f, 64f), viewportContainer,
			weatherOverlayRoot, peripheralWeatherOverlayRoot, memoryWeatherOverlayRoot,
			weatherFxRoot, peripheralWeatherFxRoot);

		ApplyLightingProfile(_lightingProfileIndex);
		UpdateCameraZoom();
	}

	public void ConfigureLighting(IsometricLightingSettings? settings = null)
	{
		var resolved = settings ?? DefaultLighting;
		if (_lighting.Equals(resolved))
			return;

		_lighting = resolved.Clamp(MinLight, MaxLight);
		_textureCache.Clear();
	}

	// ── Orchestration (Flush / Advance / Coordinate Picking / Zoom) ──

	public void SetEditorView(bool active, int centerX, int centerY, int centerZ, Vector2I? hoverWorld = null)
	{
		_editorViewActive = active;
		_viewCenterX = centerX;
		_viewCenterY = centerY;
		_viewCenterZ = centerZ;
	}

	internal void SetWeatherScreenFxTuning(WeatherScreenFxTuningSet? tuning)
		=> _weatherFxController?.SetTuning(tuning, _editorViewActive);

	public void Flush()
	{
		var frameStartUsec = Time.GetTicksUsec();
		_tileDrawCommandCount = 0;
		_weatherFxController?.BeginFrame();

		if (_state.World == null)
		{
			_weatherFxController?.ClearScreenFxTarget();
			_weatherFxController?.UpdateWeatherScreenFxOverlay(0d, _tileAnimationClockSeconds);
			_weatherFxController?.EndFrame();
			CommitPerfFrame((Time.GetTicksUsec() - frameStartUsec) / 1000.0);
			return;
		}

		if (_editorViewActive)
		{
			_fogTracker.RevealAll = true;
			_weatherFxController?.ClearScreenFxTarget();
		}
		else
		{
			_fogTracker.RevealAll = false;
			_fogTracker.Update(_state);
			_weatherFxController?.RefreshWeatherScreenFxTarget(editorViewActive: false);
			_viewCenterX = _state.PlayerX;
			_viewCenterY = _state.PlayerY;
			_viewCenterZ = _state.PlayerZ;
		}

		Render();
		_tileDrawCommandCount = _lastDrawCommandCount;
		_weatherFxController?.UpdateWeatherScreenFxOverlay(0d, _tileAnimationClockSeconds);
		_weatherFxController?.EndFrame();
		CommitPerfFrame((Time.GetTicksUsec() - frameStartUsec) / 1000.0);
	}

	public void AdvanceAnimations(double delta)
	{
		if (delta <= 0d) return;
		_tileAnimationClockSeconds += delta;
		_weatherFxController?.UpdateWeatherScreenFxOverlay(delta, _tileAnimationClockSeconds);
		AdvancePlayerCorrectionSmoothing((float)delta);
	}

	public bool IsWorldCellVisible(int wx, int wy, int wz)
	{
		if (_state.World == null) return false;
		var band = _fogTracker.GetVisionBand(wx, wy, wz);
		return band is PlayerVisionBand.Focused or PlayerVisionBand.Peripheral;
	}

	public bool TryGetWorldCellFromGlobalPosition(Vector2 globalPos, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (_viewportContainer == null || _subViewport == null || _camera == null)
			return false;

		var rect = _viewportContainer.GetGlobalRect();
		if (!rect.HasPoint(globalPos) || rect.Size.X <= 0 || rect.Size.Y <= 0)
			return false;

		var localInContainer = globalPos - rect.Position;
		var viewportPos = new Vector2(
			localInContainer.X * _subViewport.Size.X / rect.Size.X,
			localInContainer.Y * _subViewport.Size.Y / rect.Size.Y);
		var viewportSize = new Vector2(_subViewport.Size.X, _subViewport.Size.Y);
		var screenOffset = viewportPos - viewportSize / 2f;
		var mapLocal = _camera.Position + new Vector2(
			screenOffset.X / _camera.Zoom.X,
			screenOffset.Y / _camera.Zoom.Y);

		return TryPickIsometricCell(mapLocal, out worldCell);
	}

	private bool TryPickIsometricCell(Vector2 screenPos, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (_state.World == null) return false;

		var cz = _editorViewActive ? _viewCenterZ : _state.PlayerZ;
		var zMin = cz - 4;
		var zMax = cz + 2;
		for (var z = zMax; z >= zMin; z--)
		{
			var (wx, wy) = IsoCoordUtil.ScreenToWorldCell(screenPos, z);
			var terrain = _state.World.GetTerrain(wx, wy, z);
			if (terrain.StringId != Terrains.Air && terrain.StringId != Terrains.Void)
			{
				worldCell = new Vector3I(wx, wy, z);
				return true;
			}
		}

		// Editor mode: allow targeting empty cells at camera Z for block placement
		if (_editorViewActive)
		{
			var (fallbackX, fallbackY) = IsoCoordUtil.ScreenToWorldCell(screenPos, cz);
			worldCell = new Vector3I(fallbackX, fallbackY, cz);
			return true;
		}

		return false;
	}

	public bool TryGetWorldEffectPosition(int wx, int wy, int wz, out Vector2 position)
	{
		position = IsoCoordUtil.WorldToScreen(wx, wy, wz);
		return true;
	}

	public bool TryGetWorldOverlayPosition(int wx, int wy, int wz, out Vector2 position)
	{
		position = Vector2.Zero;
		var mapPos = IsoCoordUtil.WorldToScreen(wx, wy, wz);
		return TryMapToOverlayPosition(mapPos, out position);
	}

	private bool TryMapToOverlayPosition(Vector2 mapPosition, out Vector2 overlayPosition)
	{
		overlayPosition = Vector2.Zero;
		if (_camera == null || _subViewport == null || _viewportContainer == null)
			return false;

		var viewportSize = new Vector2(_subViewport.Size.X, _subViewport.Size.Y);
		if (viewportSize.X <= 0f || viewportSize.Y <= 0f)
			return false;

		var zoom = _camera.Zoom;
		var viewportPosition = viewportSize / 2f + new Vector2(
			(mapPosition.X - _camera.Position.X) * zoom.X,
			(mapPosition.Y - _camera.Position.Y) * zoom.Y);
		var containerSize = _viewportContainer.Size;
		if (containerSize.X <= 0f || containerSize.Y <= 0f)
			return false;

		overlayPosition = new Vector2(
			viewportPosition.X * containerSize.X / viewportSize.X,
			viewportPosition.Y * containerSize.Y / viewportSize.Y);
		return true;
	}

	public bool StepZoom(int direction)
	{
		if (_camera == null || direction == 0)
			return false;
		var requestedZoom = Mathf.Clamp(_zoom + direction * CameraZoomStep, _minCameraZoom, _maxCameraZoom);
		if (Mathf.IsEqualApprox(requestedZoom, _zoom))
			return false;
		_zoom = requestedZoom;
		UpdateCameraZoom();
		return true;
	}

	public void SetZoomRange(float minZoom, float maxZoom)
	{
		var normalizedMin = Mathf.Clamp(minZoom, 0.2f, 4.0f);
		var normalizedMax = Mathf.Clamp(maxZoom, 0.2f, 4.0f);
		if (normalizedMin > normalizedMax)
			(normalizedMin, normalizedMax) = (normalizedMax, normalizedMin);
		_minCameraZoom = normalizedMin;
		_maxCameraZoom = normalizedMax;
		_zoom = Mathf.Clamp(_zoom, _minCameraZoom, _maxCameraZoom);
		UpdateCameraZoom();
	}

	public bool SetZoomTo(float zoom)
	{
		if (_camera == null) return false;
		var clamped = Mathf.Clamp(zoom, _minCameraZoom, _maxCameraZoom);
		if (Mathf.IsEqualApprox(clamped, _zoom)) return false;
		_zoom = clamped;
		UpdateCameraZoom();
		return true;
	}

	private void UpdateCameraZoom()
	{
		if (_camera != null)
			_camera.Zoom = Vector2.One * _zoom;
	}

	public string? ToggleRenderMode()
		=> LocalizationService.T("render.view_mode.iso_only");

	public string CycleIsometricLightingProfile()
	{
		if (LightingProfiles.Length == 0)
			return LocalizationService.TOrFallback("render.lighting.unavailable", "Lighting profile is unavailable.");

		_lightingProfileIndex = (_lightingProfileIndex + 1) % LightingProfiles.Length;
		ApplyLightingProfile(_lightingProfileIndex);
		var profileKey = LightingProfiles[_lightingProfileIndex].Key;
		return LocalizationService.TOrFallback(
			"render.lighting.profile_changed",
			"Lighting profile switched: {profile}",
			("profile", LocalizationService.TOrFallback(profileKey, profileKey)));
	}

	public void SetLightingProfile(int profileIndex)
	{
		if (LightingProfiles.Length == 0) return;
		var clamped = Math.Clamp(profileIndex, 0, LightingProfiles.Length - 1);
		_lightingProfileIndex = clamped;
		ConfigureLighting(LightingProfiles[clamped].Lighting);
	}

	private void ApplyLightingProfile(int profileIndex) => SetLightingProfile(profileIndex);

	public string ToggleMinimap()
	{
		MinimapVisible = !MinimapVisible;
		return MinimapVisible
			? LocalizationService.T("render.minimap.unimplemented")
			: LocalizationService.T("render.minimap.closed");
	}

	public string ToggleFogMap()
	{
		FogMapVisible = !FogMapVisible;
		return FogMapVisible
			? LocalizationService.T("render.fog_map.unimplemented")
			: LocalizationService.T("render.fog_map.closed");
	}

	public bool ToggleRevealAll()
	{
		_fogTracker.RevealAll = !_fogTracker.RevealAll;
		return _fogTracker.RevealAll;
	}

	public void CenterFogMap() { }
	public void ScrollFogMap(int dx, int dy) { }
	public void ResetOverlays() { FogMapVisible = false; MinimapVisible = false; }

	public void PlaySpineAnim(string animName, bool loop, int track = 0)
		=> _playerAnim?.Play(animName, loop);

	public void QueueSpineAnim(string animName, bool loop, float delay = 0f, int track = 0) { }

	public void PlayOneShotThenIdle(string animName)
		=> _playerAnim?.PlayOneShot(animName, "Idle");

	public void ApplyPlayerCorrectionSmoothing(Vector2 worldCellOffset, float durationSeconds)
	{
		_playerVisualCorrectionOffset = worldCellOffset * new Vector2(64f, 64f);
		_playerVisualCorrectionDuration = Math.Max(0.001f, durationSeconds);
		_playerVisualCorrectionRemaining = _playerVisualCorrectionDuration;
	}

	private void AdvancePlayerCorrectionSmoothing(float deltaSeconds)
	{
		if (_playerVisualCorrectionRemaining <= 0f) return;
		_playerVisualCorrectionRemaining = Math.Max(0f, _playerVisualCorrectionRemaining - deltaSeconds);
		var ratio = _playerVisualCorrectionDuration <= 0f
			? 0f : _playerVisualCorrectionRemaining / _playerVisualCorrectionDuration;
		_playerVisualCorrectionOffset *= ratio;
		if (_playerVisualCorrectionRemaining <= 0f)
			_playerVisualCorrectionOffset = Vector2.Zero;
	}

	private void CommitPerfFrame(double frameTimeMs)
	{
		if (!_hasFrameTimeEwma)
		{
			_frameTimeEwmaMs = frameTimeMs;
			_hasFrameTimeEwma = true;
		}
		else
		{
			const double alpha = 0.10;
			_frameTimeEwmaMs = (_frameTimeEwmaMs * (1.0 - alpha)) + (frameTimeMs * alpha);
		}
		_lastPerfSnapshot = new RenderPerfSnapshot(
			(_weatherFxController?.ActiveSpriteCount ?? 0) + _spriteCount,
			_tileDrawCommandCount,
			_frameTimeEwmaMs);
	}

	public readonly record struct RenderPerfSnapshot(
		int ActiveSpriteCount,
		int DrawCommandCount,
		double FrameTimeAvgMs)
	{
		public static RenderPerfSnapshot Empty => new(0, 0, 0d);
	}

	// ── Main Render Pass ──

	public void Render()
	{
		if (_state.World == null || _root == null) return;

		_dayNight = DayNightCycle.Compute(_state.Turn);
		BeginFrame();

		var cx = _viewCenterX;
		var cy = _viewCenterY;
		var cz = _viewCenterZ;
		var halfW = _viewW / 2;
		var halfH = _viewH / 2;
		var zMin = cz - DefaultViewDepthAbove;
		var zMax = cz + DefaultViewDepthBelow;

		_drawCommands.Clear();

		for (var wy = cy - halfH; wy <= cy + halfH; wy++)
		for (var wx = cx - halfW; wx <= cx + halfW; wx++)
		for (var wz = zMax; wz >= zMin; wz--)
		{
			var terrain = _state.World.GetTerrain(wx, wy, wz);
			if (terrain.StringId == Terrains.Air || terrain.StringId == Terrains.Void)
				continue;
			if (IsFullyOccluded(wx, wy, wz))
				continue;

			var topOccluded = _state.World.GetTerrain(wx, wy, wz - 1).IsOpaque;
			var drawTop = !topOccluded;
			var drawLeft = !_state.World.GetTerrain(wx, wy + 1, wz).IsOpaque;
			var drawRight = !_state.World.GetTerrain(wx + 1, wy, wz).IsOpaque;

			// 当侧面可见但顶面被遮挡时，强制绘制暗化顶面，避免"悬浮平行四边形"
			var shadowTop = false;
			if (topOccluded && (drawLeft || drawRight))
			{
				drawTop = true;
				shadowTop = true;
			}

			if (!drawTop && !drawLeft && !drawRight)
				continue;

			_drawCommands.Add(new VoxelDrawCommand
			{
				WorldX = wx, WorldY = wy, WorldZ = wz,
				ScreenPos = IsoCoordUtil.WorldToScreen(wx, wy, wz),
				SortKey = IsoCoordUtil.SortKey(wx, wy, wz),
				Terrain = terrain,
				DrawTop = drawTop, DrawLeftSide = drawLeft, DrawRightSide = drawRight,
				ShadowTop = shadowTop,
			});
		}

		_drawCommands.Sort(static (a, b) => a.SortKey.CompareTo(b.SortKey));
		_lightMap.Rebuild(_state.World, cx, cy, cz, halfW, halfH, zMin, zMax);
		CollectEntityCommands(cx, cy, cz, halfW, halfH, zMin, zMax);
		CollectHoverHighlights(cx, cy, cz, halfW, halfH, zMin, zMax);
		_lastDrawCommandCount = _drawCommands.Count + _entityCommands.Count + _highlightCommandCount;
		RenderScene();
		EndFrame();
		UpdateCamera(cx, cy, cz);
	}

	private bool IsFullyOccluded(int wx, int wy, int wz)
	{
		var w = _state.World!;
		return w.GetTerrain(wx, wy, wz - 1).IsOpaque
			&& w.GetTerrain(wx, wy + 1, wz).IsOpaque
			&& w.GetTerrain(wx + 1, wy, wz).IsOpaque;
	}

	// ── Drawing Methods ──

	private const float ShadowTopDarken = 0.35f;

	private void DrawBlockTop(VoxelDrawCommand cmd)
	{
		if (!_terrainAtlas.TryGetRegions(cmd.Terrain.StringId, out var regions))
			return;
		var tint = GetFaceTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ, VoxelFace.Top);
		if (cmd.ShadowTop)
			tint = new Color(tint.R * ShadowTopDarken, tint.G * ShadowTopDarken, tint.B * ShadowTopDarken, tint.A);
		var xray = ComputeXRayAlpha(cmd.WorldX, cmd.WorldY, cmd.WorldZ);
		if (xray < 1f)
		{
			tint = new Color(tint.R, tint.G, tint.B, tint.A * xray);
			_xrayCells.Add((cmd.ScreenPos, cmd.SortKey));
		}
		_faceCommands.Add(new FaceSpriteCommand(
			regions.Top,
			cmd.ScreenPos,
			tint,
			cmd.SortKey));
	}

	private void DrawLeftSide(VoxelDrawCommand cmd)
	{
		if (!_terrainAtlas.TryGetRegions(cmd.Terrain.StringId, out var regions))
			return;
		var tint = GetFaceTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ, VoxelFace.Left);
		var xray = ComputeXRayAlpha(cmd.WorldX, cmd.WorldY, cmd.WorldZ);
		if (xray < 1f)
			tint = new Color(tint.R, tint.G, tint.B, tint.A * xray);
		_faceCommands.Add(new FaceSpriteCommand(
			regions.Left,
			ResolveLeftFacePosition(cmd.ScreenPos),
			tint,
			cmd.SortKey));
	}

	private void DrawRightSide(VoxelDrawCommand cmd)
	{
		if (!_terrainAtlas.TryGetRegions(cmd.Terrain.StringId, out var regions))
			return;
		var tint = GetFaceTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ, VoxelFace.Right);
		var xray = ComputeXRayAlpha(cmd.WorldX, cmd.WorldY, cmd.WorldZ);
		if (xray < 1f)
			tint = new Color(tint.R, tint.G, tint.B, tint.A * xray);
		_faceCommands.Add(new FaceSpriteCommand(
			regions.Right,
			ResolveRightFacePosition(cmd.ScreenPos),
			tint,
			cmd.SortKey));
	}

	private static Vector2 ResolveLeftFacePosition(Vector2 topCenter)
	{
		var x = topCenter.X - IsoCoordUtil.TileHalfW / 2f;
		var y = topCenter.Y + IsoCoordUtil.TileHalfH + (SideTextureHeight - 64) / 2f;
		return new Vector2(x, y);
	}

	private static Vector2 ResolveRightFacePosition(Vector2 topCenter)
	{
		var x = topCenter.X + IsoCoordUtil.TileHalfW / 2f;
		var y = topCenter.Y + IsoCoordUtil.TileHalfH + (SideTextureHeight - 64) / 2f;
		return new Vector2(x, y);
	}

	private Color GetVisionTint(int wx, int wy, int wz)
	{
		var band = _fogTracker.GetVisionBand(wx, wy, wz);
		return band switch
		{
			PlayerVisionBand.Focused => Colors.White,
			PlayerVisionBand.Peripheral => new Color(0.78f, 0.78f, 0.82f, 1.0f),
			PlayerVisionBand.Memory => new Color(0.42f, 0.42f, 0.48f, 0.88f),
			_ => new Color(0f, 0f, 0f, 1f),
		};
	}

	private Color GetFaceTint(int wx, int wy, int wz, VoxelFace face)
	{
		var visionTint = GetVisionTint(wx, wy, wz);
		if (visionTint.R <= 0f && visionTint.G <= 0f && visionTint.B <= 0f)
			return visionTint;

		var faceLight = face switch
		{
			VoxelFace.Top => _lighting.TopLight,
			VoxelFace.Left => _lighting.LeftLight,
			VoxelFace.Right => _lighting.RightLight,
			_ => 1f,
		};

		var depth = wz - _state.PlayerZ;
		var depthAttenuation = Math.Max(0.35f, 1f - depth * _lighting.DepthFalloff);
		var brightness = Math.Clamp(_lighting.Ambient * _dayNight.AmbientMultiplier * faceLight * depthAttenuation, MinLight, MaxLight);
		brightness = MathF.Pow(brightness, _lighting.Contrast);

		var ao = ComputeAmbientOcclusion(wx, wy, wz, face);
		var sunShadow = ComputeSunShadow(wx, wy, wz, face);
		var shadedBrightness = Math.Clamp(brightness * (1f - ao) * (1f - sunShadow), MinLight, MaxLight);

		// Point light contribution (additive)
		var tintR = _dayNight.SunTintR;
		var tintG = _dayNight.SunTintG;
		var tintB = _dayNight.SunTintB;

		if (_lightMap.TryGetLight(wx, wy, wz, out var cellLight))
		{
			var pointBrightness = cellLight.Intensity * 0.5f;
			shadedBrightness = Math.Clamp(shadedBrightness + pointBrightness, MinLight, MaxLight);

			// Blend point light color into tint (stronger when point light dominates)
			var blend = Math.Clamp(pointBrightness / (shadedBrightness + 0.001f) * 0.6f, 0f, 0.8f);
			tintR = tintR + (cellLight.R - tintR) * blend;
			tintG = tintG + (cellLight.G - tintG) * blend;
			tintB = tintB + (cellLight.B - tintB) * blend;
		}

		return new Color(
			Math.Clamp(visionTint.R * shadedBrightness * tintR, 0f, 1f),
			Math.Clamp(visionTint.G * shadedBrightness * tintG, 0f, 1f),
			Math.Clamp(visionTint.B * shadedBrightness * tintB, 0f, 1f),
			visionTint.A);
	}

	private float ComputeXRayAlpha(int wx, int wy, int wz)
	{
		if (!XRayEnabled || HoverWorldCell is not { } hover)
			return 1f;
		var dx = wx - hover.X;
		var dy = wy - hover.Y;
		if (Math.Abs(dx) > XRayRadius || Math.Abs(dy) > XRayRadius)
			return 1f;
		if (wx == hover.X && wy == hover.Y && wz == hover.Z)
			return 1f;
		var diagDiff = dx + dy;
		if (diagDiff >= 0 && wz < hover.Z)
			return XRayAlpha;
		return 1f;
	}

	private float ComputeAmbientOcclusion(int wx, int wy, int wz, VoxelFace face)
	{
		if (_lighting.ShadowStrength <= 0f || _lighting.OcclusionStep <= 0f)
			return 0f;
		if (_state.World == null)
			return 0f;

		var world = _state.World;
		var ao = 0f;

		switch (face)
		{
			case VoxelFace.Top:
			{
				// 8 horizontal neighbors — direct adjacency occlusion
				const float neighborWeight = 0.06f;
				if (world.GetTerrain(wx - 1, wy, wz).IsOpaque) ao += neighborWeight;
				if (world.GetTerrain(wx + 1, wy, wz).IsOpaque) ao += neighborWeight;
				if (world.GetTerrain(wx, wy - 1, wz).IsOpaque) ao += neighborWeight;
				if (world.GetTerrain(wx, wy + 1, wz).IsOpaque) ao += neighborWeight;
				if (world.GetTerrain(wx - 1, wy - 1, wz).IsOpaque) ao += neighborWeight * 0.5f;
				if (world.GetTerrain(wx + 1, wy - 1, wz).IsOpaque) ao += neighborWeight * 0.5f;
				if (world.GetTerrain(wx - 1, wy + 1, wz).IsOpaque) ao += neighborWeight * 0.5f;
				if (world.GetTerrain(wx + 1, wy + 1, wz).IsOpaque) ao += neighborWeight * 0.5f;

				// Diagonal-above checks (blocks casting overhead shadow)
				const float aboveWeight = 0.04f;
				if (world.GetTerrain(wx + 1, wy + 1, wz - 1).IsOpaque) ao += aboveWeight;
				if (world.GetTerrain(wx - 1, wy + 1, wz - 1).IsOpaque) ao += aboveWeight;
				if (world.GetTerrain(wx + 1, wy - 1, wz - 1).IsOpaque) ao += aboveWeight;
				if (world.GetTerrain(wx - 1, wy - 1, wz - 1).IsOpaque) ao += aboveWeight;

				// Concave corner bonus: two adjacent cardinal neighbors both opaque
				const float cornerBonus = 0.08f;
				var n = world.GetTerrain(wx, wy - 1, wz).IsOpaque;
				var s = world.GetTerrain(wx, wy + 1, wz).IsOpaque;
				var w = world.GetTerrain(wx - 1, wy, wz).IsOpaque;
				var e = world.GetTerrain(wx + 1, wy, wz).IsOpaque;
				if (n && w) ao += cornerBonus;
				if (n && e) ao += cornerBonus;
				if (s && w) ao += cornerBonus;
				if (s && e) ao += cornerBonus;
				break;
			}
			case VoxelFace.Left:
			{
				// Left face is visible from -Y direction; occluded by +Y neighbors
				const float sideWeight = 0.10f;
				const float aboveSideWeight = 0.06f;
				if (world.GetTerrain(wx, wy + 1, wz).IsOpaque) ao += sideWeight;
				if (world.GetTerrain(wx, wy + 1, wz - 1).IsOpaque) ao += aboveSideWeight;
				if (world.GetTerrain(wx - 1, wy + 1, wz).IsOpaque) ao += sideWeight * 0.5f;
				// Block directly above darkens side face
				if (world.GetTerrain(wx, wy, wz - 1).IsOpaque) ao += aboveSideWeight;
				break;
			}
			case VoxelFace.Right:
			{
				// Right face is visible from -X direction; occluded by +X neighbors
				const float sideWeight = 0.10f;
				const float aboveSideWeight = 0.06f;
				if (world.GetTerrain(wx + 1, wy, wz).IsOpaque) ao += sideWeight;
				if (world.GetTerrain(wx + 1, wy, wz - 1).IsOpaque) ao += aboveSideWeight;
				if (world.GetTerrain(wx + 1, wy - 1, wz).IsOpaque) ao += sideWeight * 0.5f;
				// Block directly above darkens side face
				if (world.GetTerrain(wx, wy, wz - 1).IsOpaque) ao += aboveSideWeight;
				break;
			}
		}

		return Math.Clamp(ao * _lighting.ShadowStrength, 0f, 0.65f);
	}

	private float ComputeSunShadow(int wx, int wy, int wz, VoxelFace face)
	{
		if (_dayNight.SunAltitude <= 0.01f)
			return 0f; // no sun → no sun shadow
		if (_lighting.ShadowStrength <= 0f)
			return 0f;
		if (_state.World == null)
			return 0f;

		var world = _state.World;

		// Shadow length inversely proportional to sun altitude (longer at dawn/dusk)
		var maxSteps = (int)Math.Clamp(3f / Math.Max(0.3f, _dayNight.SunAltitude), 2, 8);

		// Sun direction: where the sun IS. Shadow is cast opposite.
		// We ray-march FROM the cell TOWARD the sun to find occluders above.
		var dirX = _dayNight.SunDirectionX;
		var dirY = _dayNight.SunDirectionY;

		var shadow = 0f;
		for (var step = 1; step <= maxSteps; step++)
		{
			var sampleX = wx + (int)MathF.Round(dirX * step);
			var sampleY = wy + (int)MathF.Round(dirY * step);
			var sampleZ = wz - step; // check cells above

			if (world.GetTerrain(sampleX, sampleY, sampleZ).IsOpaque)
			{
				// Closer occluders cast stronger shadows (inverse-distance falloff)
				var contribution = _lighting.OcclusionStep * (1f - (step - 1) / (float)(maxSteps + 1));
				shadow += contribution;
			}
		}

		var faceScale = face switch
		{
			VoxelFace.Top => 0.78f,
			VoxelFace.Left => 1.10f,
			VoxelFace.Right => 0.92f,
			_ => 1f,
		};

		return Math.Clamp(shadow * _lighting.ShadowStrength * faceScale, 0f, 0.72f);
	}

	// ── Texture Generation ──

	private CachedBlockTextures GetOrCreateTextures(TerrainDef terrain)
	{
		if (_textureCache.TryGetValue(terrain.StringId, out var cached))
			return cached;

		if (TryCreateVoxelFaceTextures(terrain, out var voxelTextures))
		{
			_textureCache[terrain.StringId] = voxelTextures;
			return voxelTextures;
		}

		// Fallback: procedural color-based diamond
		var color = TerrainColors.GetValueOrDefault(terrain.StringId, new Color(0.5f, 0.5f, 0.5f));
		var topImage = CreateDiamondImage(128, 64, color);
		var topTexture = ImageTexture.CreateFromImage(topImage);

		var leftImage = GenerateLeftSideImage(topImage);
		var rightImage = GenerateRightSideImage(topImage);

		var result = new CachedBlockTextures(
			topTexture,
			ImageTexture.CreateFromImage(leftImage),
			ImageTexture.CreateFromImage(rightImage));

		_textureCache[terrain.StringId] = result;
		return result;
	}

	private bool TryCreateVoxelFaceTextures(TerrainDef terrain, out CachedBlockTextures textures)
	{
		textures = default;
		var topPath = ResolveVoxelTopTexturePath(terrain);
		if (string.IsNullOrWhiteSpace(topPath))
			return false;

		var topSourceTexture = GetOrLoadVoxelFaceTexture(topPath);
		if (topSourceTexture == null)
			return false;

		var topSourceImage = ExtractImage(topSourceTexture);
		if (topSourceImage == null)
			return false;

		var topDiamondImage = VoxelFaceImageUtil.BuildTopDiamond(topSourceImage);
		topDiamondImage = VoxelFaceImageUtil.EnhanceTopFaceEdges(topDiamondImage, GetTopEdgeStrength(terrain));
		var topTexture = ImageTexture.CreateFromImage(topDiamondImage);

		Image sideSourceImage;
		var sidePath = ResolveVoxelSideTexturePath(terrain);
		var sideTexture = string.IsNullOrWhiteSpace(sidePath) ? null : GetOrLoadVoxelFaceTexture(sidePath);
		if (sideTexture != null)
			sideSourceImage = ExtractImage(sideTexture) ?? topSourceImage;
		else
			sideSourceImage = topSourceImage;

		var wallLike = IsWallTerrain(terrain);
		var leftDarken = wallLike ? WallLeftSideDarken : DefaultLeftSideDarken;
		var rightDarken = wallLike ? WallRightSideDarken : DefaultRightSideDarken;
		var faceHeight = wallLike ? WallSideFaceHeight : SideFaceHeight;
		var leftImage = VoxelFaceImageUtil.GenerateSideFace(sideSourceImage, isRight: false, leftDarken, faceHeight);
		var rightImage = VoxelFaceImageUtil.GenerateSideFace(sideSourceImage, isRight: true, rightDarken, faceHeight);
		VoxelFaceImageUtil.EnhanceSideFaceEdge(leftImage, isRight: false, edgeStrength: GetSideEdgeStrength(terrain));
		VoxelFaceImageUtil.EnhanceSideFaceEdge(rightImage, isRight: true, edgeStrength: GetSideEdgeStrength(terrain));

		textures = new CachedBlockTextures(
			topTexture,
			ImageTexture.CreateFromImage(leftImage),
			ImageTexture.CreateFromImage(rightImage));
		return true;
	}

	private Texture2D? GetOrLoadVoxelFaceTexture(string path)
	{
		if (_voxelFaceTextureCache.TryGetValue(path, out var cached))
			return cached;

		var loaded = GD.Load<Texture2D>(path);
		_voxelFaceTextureCache[path] = loaded;
		return loaded;
	}

	private static readonly Dictionary<string, string> VoxelTileAliases = new(StringComparer.OrdinalIgnoreCase)
	{
		["grass_top"] = "tile_grass_top.png",
		["grass_side"] = "tile_grass_side.png",
		["dirt"] = "tile_dirt.png",
		["dirt_side"] = "tile_dirt.png",
		["soil"] = "tile_dirt.png",
		["soil_side"] = "tile_dirt.png",
		["stone"] = "tile_stone.png",
		["stone_side"] = "tile_stone.png",
		["sand"] = "tile_sand.png",
		["sand_side"] = "tile_sand.png",
		["gravel"] = "tile_gravel.png",
		["gravel_side"] = "tile_gravel.png",
		["mud"] = "tile_mud.png",
		["mud_side"] = "tile_mud.png",
		["clay"] = "tile_clay.png",
		["clay_side"] = "tile_clay.png",
		["snow"] = "tile_snow.png",
		["snow_side"] = "tile_snow.png",
		["ash"] = "tile_ash.png",
		["ash_side"] = "tile_ash.png",
		["plank"] = "tile_plank.png",
		["plank_side"] = "tile_plank.png",
		["log_top"] = "tile_log_top.png",
		["log_side"] = "tile_log_side.png",
		["brick"] = "tile_brick.png",
		["brick_side"] = "tile_brick.png",
		["brick_mossy"] = "tile_brick_mossy.png",
		["brick_mossy_side"] = "tile_brick_mossy.png",
		["brick_cracked"] = "tile_brick_cracked.png",
		["brick_cracked_side"] = "tile_brick_cracked.png",
		["ore_coal"] = "ores/tile_stone_ore_coal.png",
		["ore_iron"] = "ores/tile_stone_ore_iron.png",
		["ore_copper"] = "ores/tile_stone_ore_copper.png",
		["ore_gold"] = "ores/tile_stone_ore_gold.png",
		["ore_crystal"] = "ores/tile_stone_ore_crystal.png",
		["wall_stone_side"] = "tile_stone.png",
		["wall_granite_side"] = "tile_stone.png",
		["wall_obsidian_side"] = "tile_stone.png",
		["wall_iron_side"] = "tile_stone.png",
		["mountain_side"] = "tile_stone.png",
		["rubble"] = "tile_gravel.png",
		["rubble_side"] = "tile_gravel.png",
	};

	private static string ResolveVoxelTopTexturePath(TerrainDef terrain)
	{
		var token = string.IsNullOrWhiteSpace(terrain.TopTile) ? terrain.StringId : terrain.TopTile;
		var fileName = ResolveVoxelFileName(token, isTop: true);
		return string.IsNullOrWhiteSpace(fileName) ? string.Empty : $"{VoxelTileRoot}/{fileName}";
	}

	private static string ResolveVoxelSideTexturePath(TerrainDef terrain)
	{
		var token = string.IsNullOrWhiteSpace(terrain.SideTile) ? terrain.StringId : terrain.SideTile;
		var fileName = ResolveVoxelFileName(token, isTop: false);
		return string.IsNullOrWhiteSpace(fileName) ? string.Empty : $"{VoxelTileRoot}/{fileName}";
	}

	private static string ResolveVoxelFileName(string token, bool isTop)
	{
		if (VoxelTileAliases.TryGetValue(token, out var alias))
			return alias;

		var inferred = token switch
		{
			"grass_block" => isTop ? "tile_grass_top.png" : "tile_grass_side.png",
			"grass" => isTop ? "tile_grass_top.png" : "tile_grass_side.png",
			"tree" => "tile_grass_side.png",
			"fungus" => "tile_grass_side.png",
			"dirt" => "tile_dirt.png",
			"swamp" => "tile_dirt.png",
			"marsh" => "tile_dirt.png",
			"sand" => "tile_dirt.png",
			"wall_soil" => "tile_dirt.png",
			"stone" => "tile_stone.png",
			"gravel" => "tile_stone.png",
			"mountain" => "tile_stone.png",
			"rubble" => "tile_stone.png",
			"floor" => "tile_stone.png",
			"wall_stone" => "tile_stone.png",
			"wall_granite" => "tile_stone.png",
			"wall_obsidian" => "tile_stone.png",
			"wall_iron" => "tile_stone.png",
			"crystal_vein" => "tile_stone.png",
			_ => string.Empty,
		};

		return inferred;
	}

	private static float GetTopEdgeStrength(TerrainDef terrain)
	{
		if (IsWallTerrain(terrain))
			return WallTopEdgeStrength;
		return terrain.Solid ? SolidTopEdgeStrength : NonSolidTopEdgeStrength;
	}

	private static float GetSideEdgeStrength(TerrainDef terrain)
	{
		if (IsWallTerrain(terrain))
			return WallSideEdgeStrength;
		return terrain.Solid ? SolidSideEdgeStrength : NonSolidSideEdgeStrength;
	}

	private static bool IsWallTerrain(TerrainDef terrain)
	{
		return terrain.StringId.StartsWith("wall_", StringComparison.OrdinalIgnoreCase)
			|| terrain.StringId.Equals(Terrains.Stone, StringComparison.OrdinalIgnoreCase)
			|| terrain.StringId.Equals(Terrains.Dirt, StringComparison.OrdinalIgnoreCase)
			|| terrain.StringId.Equals(Terrains.Mountain, StringComparison.OrdinalIgnoreCase);
	}

	/// <summary>
	/// Extract the top tile as an Image from an AtlasTexture or regular Texture2D.
	/// </summary>
	private static Image? ExtractImage(Texture2D texture)
	{
		if (texture is AtlasTexture atlas)
		{
			var fullImage = atlas.Atlas?.GetImage();
			if (fullImage == null) return null;
			var region = atlas.Region;
			return fullImage.GetRegion(new Rect2I(
				(int)region.Position.X, (int)region.Position.Y,
				(int)region.Size.X, (int)region.Size.Y));
		}
		return texture.GetImage();
	}

	/// <summary>
	/// Generate left side face as a 64x64 parallelogram image.
	/// The parallelogram covers the area below the diamond's bottom-left edge:
	///   TL=(0,0) TR=(63,31) BR=(63,63) BL=(0,32)  (in image coords)
	/// Colors are sampled from the left-bottom edge of the top diamond, darkened by LeftDarken.
	/// </summary>
	private static Image GenerateLeftSideImage(Image topImage)
	{
		const int iw = SideTextureWidth;
		const int ih = SideTextureHeight;
		const int faceH = SideFaceHeight;
		var img = Image.CreateEmpty(iw, ih, false, Image.Format.Rgba8);
		var tw = topImage.GetWidth();
		var th = topImage.GetHeight();
		var halfW = tw / 2;
		var halfH = th / 2;

		for (var px = 0; px < iw; px++)
		{
			var t = px / (float)(iw - 1);
			var sampleX = (int)(t * halfW);
			var sampleY = halfH + (int)(t * (halfH - 1));
			sampleX = Math.Clamp(sampleX, 0, tw - 1);
			sampleY = Math.Clamp(sampleY, 0, th - 1);
			var color = VoxelFaceImageUtil.SampleArea(topImage, sampleX, sampleY, tw, th);

			var pyStart = (int)Math.Round(px * IsoCoordUtil.TileHalfH / (double)(iw - 1));
			for (var dy = 0; dy < faceH; dy++)
			{
				var py = pyStart + dy;
				if (py >= ih) break;
				var gradientFactor = 1.0f - (dy / (float)faceH) * 0.2f;
				var c = color * new Color(LeftDarken * gradientFactor, LeftDarken * gradientFactor, LeftDarken * gradientFactor, 1f);
				c.A = color.A;
				img.SetPixel(px, py, c);
			}
		}
		return img;
	}

	/// <summary>
	/// Generate right side face as a 64x64 parallelogram image.
	/// The parallelogram covers the area below the diamond's bottom-right edge:
	///   TL=(0,32) TR=(63,0) BR=(63,32) BL=(0,64)  (in image coords)
	/// Colors are sampled from the right-bottom edge of the top diamond, darkened by RightDarken.
	/// </summary>
	private static Image GenerateRightSideImage(Image topImage)
	{
		const int iw = SideTextureWidth;
		const int ih = SideTextureHeight;
		const int faceH = SideFaceHeight;
		var img = Image.CreateEmpty(iw, ih, false, Image.Format.Rgba8);
		var tw = topImage.GetWidth();
		var th = topImage.GetHeight();
		var halfW = tw / 2;
		var halfH = th / 2;

		for (var px = 0; px < iw; px++)
		{
			var t = px / (float)(iw - 1);
			var sampleX = halfW + (int)(t * (halfW - 1));
			var sampleY = (th - 1) - (int)(t * (halfH - 1));
			sampleX = Math.Clamp(sampleX, 0, tw - 1);
			sampleY = Math.Clamp(sampleY, 0, th - 1);
			var color = VoxelFaceImageUtil.SampleArea(topImage, sampleX, sampleY, tw, th);

			var pyStart = (int)Math.Round((iw - 1 - px) * IsoCoordUtil.TileHalfH / (double)(iw - 1));
			for (var dy = 0; dy < faceH; dy++)
			{
				var py = pyStart + dy;
				if (py >= ih) break;
				var gradientFactor = 1.0f - (dy / (float)faceH) * 0.2f;
				var c = color * new Color(RightDarken * gradientFactor, RightDarken * gradientFactor, RightDarken * gradientFactor, 1f);
				c.A = color.A;
				img.SetPixel(px, py, c);
			}
		}
		return img;
	}

	/// <summary>Create a solid-color diamond image (fallback when no atlas tile available).</summary>
	private static Image CreateDiamondImage(int w, int h, Color color)
	{
		var image = Image.CreateEmpty(w, h, false, Image.Format.Rgba8);
		var halfW = w / 2;
		var halfH = h / 2;
		for (var py = 0; py < h; py++)
		for (var px = 0; px < w; px++)
		{
			var dx = Math.Abs(px - halfW) / (float)halfW;
			var dy = Math.Abs(py - halfH) / (float)halfH;
			image.SetPixel(px, py, dx + dy <= 1.0f ? color : Colors.Transparent);
		}
		return image;
	}

	// ── Entity Rendering ──

	private static readonly Vector2 DefaultEntitySpriteScale = new(0.25f, 0.25f);
	private static readonly Vector2 EntitySpriteBaseOffset = new(0f, -8f);
	private readonly Dictionary<string, ImageTexture> _entityMarkerCache = new();

	private void CollectEntityCommands(int cx, int cy, int cz, int halfW, int halfH, int zMin, int zMax)
	{
		_entityCommands.Clear();

		foreach (var actor in _state.Actors.Values)
		{
			if (actor.Z < zMin || actor.Z > zMax) continue;
			if (Math.Abs(actor.X - cx) > halfW || Math.Abs(actor.Y - cy) > halfH) continue;
			if (_fogTracker.GetVisionBand(actor.X, actor.Y, actor.Z) == PlayerVisionBand.Unknown) continue;
			var tint = GetVisionTint(actor.X, actor.Y, actor.Z);
			var label = actor.Id == _state.PlayerId ? "P" : (actor.Faction == Factions.Hostile ? "!" : "?");
			_entityCommands.Add(new EntityDrawCommand(
				IsoCoordUtil.SortKey(actor.X, actor.Y, actor.Z),
				IsoCoordUtil.WorldToScreen(actor.X, actor.Y, actor.Z),
				actor,
				label,
				tint));
		}

		for (var wy = cy - halfH; wy <= cy + halfH; wy++)
		for (var wx = cx - halfW; wx <= cx + halfW; wx++)
		for (var wz = zMax; wz >= zMin; wz--)
		{
			var entities = _state.World!.GetEntities(wx, wy, wz);
			if (entities.Count == 0) continue;
			if (_fogTracker.GetVisionBand(wx, wy, wz) == PlayerVisionBand.Unknown) continue;
			var tint = GetVisionTint(wx, wy, wz);
			var pos = IsoCoordUtil.WorldToScreen(wx, wy, wz);
			var key = IsoCoordUtil.SortKey(wx, wy, wz);
			foreach (var e in entities)
				_entityCommands.Add(new EntityDrawCommand(key, pos, null, e.Glyph, tint));
		}

		_entityCommands.Sort(static (a, b) => a.SortKey.CompareTo(b.SortKey));
	}

	private void RenderScene()
	{
		_faceCommands.Clear();
		_xrayCells.Clear();

		for (var i = 0; i < _drawCommands.Count; i++)
		{
			var terrain = _drawCommands[i];
			if (terrain.DrawTop) DrawBlockTop(terrain);
			if (terrain.DrawLeftSide) DrawLeftSide(terrain);
			if (terrain.DrawRightSide) DrawRightSide(terrain);
		}

		_faceCommands.Sort(static (a, b) => a.SortKey.CompareTo(b.SortKey));
		_faceBatchCanvas?.SetCommands(_faceCommands);

		for (var i = 0; i < _entityCommands.Count; i++)
		{
			var entity = _entityCommands[i];
			if (entity.Actor != null && TryDrawActorSprite(entity.ScreenPos, entity.Actor, entity.Tint))
				continue;
			DrawEntityMarker(entity.ScreenPos, entity.Label, entity.Tint);
		}

		RenderHoverHighlights();
		RenderXRayOutlines();
	}

	private void CollectHoverHighlights(int cx, int cy, int cz, int halfW, int halfH, int zMin, int zMax)
	{
		_highlightCommands.Clear();
		_highlightCommandCount = 0;
		if (HoverWorldCell is not { } hover)
			return;
		if (Math.Abs(hover.X - cx) > halfW || Math.Abs(hover.Y - cy) > halfH)
			return;
		if (hover.Z < zMin || hover.Z > zMax)
			return;
		if (_fogTracker.GetVisionBand(hover.X, hover.Y, hover.Z) == PlayerVisionBand.Unknown)
			return;

		var basePos = IsoCoordUtil.WorldToScreen(hover.X, hover.Y, hover.Z);
		_highlightCommands.Add(new HoverHighlightCommand(basePos, HoverCellTint, IsoCoordUtil.SortKey(hover.X, hover.Y, hover.Z) + 9000));
		_highlightCommandCount = _highlightCommands.Count;
	}

	private void RenderHoverHighlights()
	{
		var pulse = 0.55f + 0.45f * (0.5f + 0.5f * Mathf.Sin(Time.GetTicksMsec() / 320.0f));
		for (var i = 0; i < _highlightCommands.Count; i++)
		{
			var command = _highlightCommands[i];
			var fillTint = command.Tint * new Color(1f, 1f, 1f, pulse);
			DrawHoverDiamond(command.ScreenPos, HoverCellOutlineTint, HoverCellOutlineScale, zIndex: 2, textureKey: "hover_diamond_outline");
			DrawHoverDiamond(command.ScreenPos, fillTint, HoverCellFillScale, zIndex: 3, textureKey: "hover_diamond_fill");
			DrawHoverLightWalls(command.ScreenPos, pulse);
		}
	}

	private void RenderXRayOutlines()
	{
		for (var i = 0; i < _xrayCells.Count; i++)
		{
			var (pos, _) = _xrayCells[i];
			DrawHoverDiamond(pos, XRayOutlineTint, XRayOutlineScale, zIndex: 1, textureKey: "hover_diamond_outline");
		}
	}

	/// <summary>
	/// 在菱形四角绘制向上渐隐的光柱 + 顶部连线，营造立体光笼选择框效果。
	/// </summary>
	private void DrawHoverLightWalls(Vector2 cellPos, float pulse)
	{
		const float wallH = 28f;
		var wallTint = HoverWallTint * new Color(1f, 1f, 1f, pulse);

		// 菱形4个顶点偏移（相对于 cellPos）
		Vector2 top = new(0f, -31f), right = new(63f, 0f),
		        bottom = new(0f, 31f), left = new(-63f, 0f);

		// 四角光柱：从顶点向上延伸的竖直渐隐光条
		DrawCornerPillar(cellPos + top, wallH, wallTint);
		DrawCornerPillar(cellPos + right, wallH, wallTint);
		DrawCornerPillar(cellPos + bottom, wallH, wallTint);
		DrawCornerPillar(cellPos + left, wallH, wallTint);

		// 顶部横向连线：在光柱顶端之间绘制淡化水平线，形成笼顶
		var capTint = wallTint * new Color(1f, 1f, 1f, 0.4f);
		DrawWallCap(cellPos + top + new Vector2(0f, -wallH),
		            cellPos + right + new Vector2(0f, -wallH), capTint);
		DrawWallCap(cellPos + right + new Vector2(0f, -wallH),
		            cellPos + bottom + new Vector2(0f, -wallH), capTint);
		DrawWallCap(cellPos + bottom + new Vector2(0f, -wallH),
		            cellPos + left + new Vector2(0f, -wallH), capTint);
		DrawWallCap(cellPos + left + new Vector2(0f, -wallH),
		            cellPos + top + new Vector2(0f, -wallH), capTint);
	}

	private void DrawCornerPillar(Vector2 basePos, float height, Color tint)
	{
		var sprite = AcquireSprite();
		sprite.Centered = false;
		sprite.Texture = GetEntityMarkerTexture("hover_wall_pillar");
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Linear;
		sprite.RegionEnabled = false;
		sprite.Rotation = 0f;
		sprite.Skew = 0f;
		// 纹理 4x32：宽度保持 1:1（~4px），高度缩放到实际光柱高度
		sprite.Scale = new Vector2(1f, height / 32f);
		// 从基准点向上延伸，水平居中
		sprite.Position = new Vector2(basePos.X - 2f, basePos.Y - height);
		sprite.ZIndex = 4;
		sprite.Modulate = tint;
		sprite.Visible = true;
	}

	private void DrawWallCap(Vector2 from, Vector2 to, Color tint)
	{
		var mid = (from + to) * 0.5f;
		var dir = to - from;
		var len = dir.Length();
		if (len < 1f) return;

		var sprite = AcquireSprite();
		sprite.Centered = true;
		sprite.Texture = GetEntityMarkerTexture("hover_wall_cap");
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Linear;
		sprite.RegionEnabled = false;
		sprite.Skew = 0f;
		// 纹理 32x4：水平拉伸到边长
		sprite.Scale = new Vector2(len / 32f, 1f);
		sprite.Position = mid;
		sprite.Rotation = dir.Angle();
		sprite.ZIndex = 4;
		sprite.Modulate = tint;
		sprite.Visible = true;
	}

	private void DrawHoverDiamond(Vector2 pos, Color tint, Vector2 scale, int zIndex, string textureKey)
	{
		var sprite = AcquireSprite();
		sprite.Centered = true;
		sprite.Texture = GetEntityMarkerTexture(textureKey);
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Linear;
		sprite.RegionEnabled = false;
		sprite.Scale = scale;
		sprite.Position = pos;
		sprite.Skew = 0f;
		sprite.ZIndex = zIndex;
		sprite.Modulate = tint;
		sprite.Visible = true;
	}

	private bool TryDrawActorSprite(Vector2 pos, Actor actor, Color tint)
	{
		if (!TryResolveActorSpriteVisual(actor, out var visual))
			return false;

		var size = visual.Region?.Size ?? visual.Texture.GetSize();
		var sprite = AcquireSprite();
		sprite.Centered = false;
		sprite.Texture = visual.Texture;
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Nearest;
		sprite.RegionEnabled = visual.Region != null;
		if (visual.Region is { } region)
			sprite.RegionRect = region;
		sprite.Scale = visual.Scale;
		sprite.Skew = 0f;
		sprite.ZIndex = 1;
		sprite.Modulate = tint;
		sprite.Position = pos + EntitySpriteBaseOffset + visual.Offset + new Vector2(
			-(size.X * visual.Scale.X) / 2f,
			-(size.Y * visual.Scale.Y));
		sprite.Visible = true;
		return true;
	}

	private bool TryResolveActorSpriteVisual(Actor actor, out ActorSpriteVisual visual)
	{
		visual = default;
		var entry = ResolveActorRenderEntry(actor);
		if (entry == null)
			return false;

		Texture2D? texture = null;
		Rect2? region = null;
		if (IsTextureEntry(entry) && entry.TexturePath is { Length: > 0 } texturePath)
		{
			texture = ResAccess.Get<Texture2D>(texturePath);
			if (texture != null)
				region = ResolveEntitySpriteRegion(entry, actor, texture);
		}
		else if (IsSpriteSheetEntry(entry))
		{
			var sheetPath = ResolveCharacterSheetPath(entry);
			if (sheetPath.Length > 0)
			{
				texture = ResAccess.Get<Texture2D>(sheetPath);
				if (texture != null)
					region = ResolveCharacterSheetRegion(entry, actor, texture);
			}
		}

		if (texture == null)
			return false;

		visual = new ActorSpriteVisual(
			texture,
			region,
			ResolveEntitySpriteScale(entry.Scale),
			ResolveEntitySpriteOffset(entry.Offset));
		return true;
	}

	private static Vector2 ResolveEntitySpriteScale(float[]? scale)
	{
		if (scale is [var x, var y] && x > 0f && y > 0f)
			return new Vector2(x, y);
		return DefaultEntitySpriteScale;
	}

	private static Vector2 ResolveEntitySpriteOffset(float[]? offset)
	{
		if (offset is [var x, var y])
			return new Vector2(x, y);
		return Vector2.Zero;
	}

	private static Rect2? ResolveEntitySpriteRegion(ResAccess.RenderEntry entry, Actor actor, Texture2D texture)
	{
		if (!entry.UseFacing)
			return null;

		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		var frameWidth = entry.FrameWidth > 0 ? Math.Min(entry.FrameWidth, textureWidth) : textureWidth;
		var inferredFrameHeight = textureHeight % 8 == 0 ? textureHeight / 8 : textureHeight;
		var frameHeight = entry.FrameHeight > 0 ? Math.Min(entry.FrameHeight, textureHeight) : inferredFrameHeight;
		if (frameWidth <= 0 || frameHeight <= 0)
			return null;

		var rowCount = Math.Max(1, textureHeight / frameHeight);
		var row = Math.Clamp(
			DirectionalSpriteHelper.ResolveDirectionRow(actor.FacingX, actor.FacingY),
			0,
			rowCount - 1);
		return new Rect2(0, row * frameHeight, frameWidth, frameHeight);
	}

	private ResAccess.RenderEntry? ResolveActorRenderEntry(Actor actor)
	{
		if (actor.Id == _state.PlayerId)
		{
			var appearance = PlayerAppearanceCatalog.GetOrDefault(_state.PlayerAppearanceId);
			var tuning = ResAccess.GetEntry("player");
			return new ResAccess.RenderEntry
			{
				Type = "sprite_sheet",
				SheetDir = appearance.SheetDir,
				DefaultAnim = appearance.DefaultAnim,
				Scale = tuning?.Scale,
				Offset = tuning?.Offset,
				FrameWidth = tuning?.FrameWidth ?? 0,
				FrameHeight = tuning?.FrameHeight ?? 0,
				UseFacing = true,
			};
		}

		if (TryGetSupportedActorEntry(actor.Id, out var direct))
			return direct;
		if (!string.IsNullOrWhiteSpace(actor.TemplateId) && TryGetSupportedActorEntry(actor.TemplateId, out var template))
			return template;
		if (actor.Race?.Id is { Length: > 0 } raceId && TryGetSupportedActorEntry(raceId, out var race))
			return race;

		return null;
	}

	private static bool TryGetSupportedActorEntry(string key, out ResAccess.RenderEntry? entry)
	{
		entry = ResAccess.GetEntry(key);
		return IsTextureEntry(entry) || IsSpriteSheetEntry(entry);
	}

	private static bool IsSpriteSheetEntry(ResAccess.RenderEntry? entry) =>
		entry != null
		&& string.Equals(entry.Type, "sprite_sheet", StringComparison.OrdinalIgnoreCase)
		&& !string.IsNullOrWhiteSpace(entry.SheetDir);

	private static string ResolveCharacterSheetPath(ResAccess.RenderEntry entry)
	{
		if (string.IsNullOrWhiteSpace(entry.SheetDir))
			return string.Empty;
		var animationKey = string.IsNullOrWhiteSpace(entry.DefaultAnim) ? "Idle" : entry.DefaultAnim!;
		var sheetKey = CharacterSheetMap.TryGetValue(animationKey, out var resolved) ? resolved : "Idle";
		return $"{entry.SheetDir!.TrimEnd('/')}/{sheetKey}.png";
	}

	private static Rect2? ResolveCharacterSheetRegion(ResAccess.RenderEntry entry, Actor actor, Texture2D texture)
	{
		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		var frameWidth = entry.FrameWidth > 0
			? Math.Min(entry.FrameWidth, textureWidth)
			: Math.Min(DefaultCharacterSheetFrameWidth, textureWidth);
		var frameHeight = entry.FrameHeight > 0
			? Math.Min(entry.FrameHeight, textureHeight)
			: Math.Min(DefaultCharacterSheetFrameHeight, textureHeight);
		if (frameWidth <= 0 || frameHeight <= 0)
			return null;

		var rowCount = Math.Max(1, textureHeight / frameHeight);
		var row = Math.Clamp(
			DirectionalSpriteHelper.ResolveDirectionRow(actor.FacingX, actor.FacingY),
			0,
			rowCount - 1);
		return new Rect2(0, row * frameHeight, frameWidth, frameHeight);
	}

	private static bool IsTextureEntry(ResAccess.RenderEntry? entry) =>
		entry != null
		&& string.Equals(entry.Type, "texture", StringComparison.OrdinalIgnoreCase)
		&& !string.IsNullOrWhiteSpace(entry.TexturePath);

	private void DrawEntityMarker(Vector2 pos, string label, Color tint)
	{
		var s = AcquireSprite();
		s.Centered = true;
		s.RegionEnabled = false;
		s.Scale = Vector2.One;
		s.Texture = GetEntityMarkerTexture(label);
		s.Position = pos - new Vector2(0, IsoCoordUtil.TileHalfH * 0.5f);
		s.Skew = 0f;
		s.ZIndex = 1;
		s.Modulate = tint;
		s.Visible = true;
	}

	private ImageTexture GetEntityMarkerTexture(string label)
	{
		if (_entityMarkerCache.TryGetValue(label, out var cached)) return cached;

		if (label is "hover_wall_pillar" or "hover_wall_cap")
		{
			// 光柱: 4x32 竖直渐变（底亮顶透明）
			// 顶部连线: 32x4 水平渐变（中间亮两端淡）
			var isVert = label == "hover_wall_pillar";
			int w = isVert ? 4 : 32, h = isVert ? 32 : 4;
			var img = Image.CreateEmpty(w, h, false, Image.Format.Rgba8);
			for (var py = 0; py < h; py++)
			for (var px = 0; px < w; px++)
			{
				float a;
				if (isVert)
				{
					// 底部(py=h-1)最亮，顶部(py=0)全透明
					var t = (float)py / (h - 1);
					var vertFade = t * t; // 二次曲线：顶部快速衰减
					var cx = Math.Abs(px - (w - 1) * 0.5f) / (w * 0.5f);
					a = vertFade * (1f - cx * cx);
				}
				else
				{
					// 中心最亮，两端渐淡
					var nx = Math.Abs(px - (w - 1) * 0.5f) / (w * 0.5f);
					var ny = Math.Abs(py - (h - 1) * 0.5f) / (h * 0.5f);
					a = (1f - nx * nx) * (1f - ny * ny);
				}
				img.SetPixel(px, py, new Color(1f, 1f, 1f, a));
			}
			var wallTex = ImageTexture.CreateFromImage(img);
			_entityMarkerCache[label] = wallTex;
			return wallTex;
		}

		const int size = 64;
		var image = Image.CreateEmpty(size, size, false, Image.Format.Rgba8);
		var center = (size - 1) * 0.5f;
		var radius = size * 0.5f - 4f;
		var color = label switch
		{
			"P" => new Color(0.2f, 0.6f, 1.0f),
			"!" => new Color(1.0f, 0.2f, 0.2f),
			"?" => new Color(0.2f, 0.8f, 0.2f),
			_ => Colors.White,
		};
		for (var py = 0; py < size; py++)
		for (var px = 0; px < size; px++)
		{
			if (label is "hover_diamond_fill" or "hover_diamond_outline")
			{
				var nx = Math.Abs(px - center) / (size * 0.5f);
				var ny = Math.Abs(py - center) / (size * 0.5f);
				var d = nx + ny;
				if (d > 1f)
				{
					image.SetPixel(px, py, Colors.Transparent);
					continue;
				}

				if (label == "hover_diamond_outline")
				{
					var edgeAlpha = Math.Clamp((d - 0.85f) / 0.15f, 0f, 1f);
					var innerFade = 1f - Math.Clamp((d - 0.15f) / 0.45f, 0f, 1f);
					var alpha = Math.Max(edgeAlpha, innerFade * 0.06f);
					image.SetPixel(px, py, new Color(color.R, color.G, color.B, alpha));
				}
				else
				{
					var edgeSoft = 1f - Math.Clamp((d - 0.80f) / 0.20f, 0f, 1f);
					var centerGlow = 1f - Math.Clamp(d / 0.72f, 0f, 1f);
					var alpha = Math.Clamp(0.22f + centerGlow * 0.62f + edgeSoft * 0.22f, 0f, 1f);
					image.SetPixel(px, py, new Color(color.R, color.G, color.B, alpha));
				}
				continue;
			}

			var dx = px - center;
			var dy = py - center;
			image.SetPixel(px, py, dx * dx + dy * dy <= radius * radius ? color : Colors.Transparent);
		}
		var tex = ImageTexture.CreateFromImage(image);
		_entityMarkerCache[label] = tex;
		return tex;
	}

	// ── Sprite Pool ──

	private void BeginFrame()
	{
		_spriteCount = 0;
		_faceBatchCanvas?.SetCommands(Array.Empty<FaceSpriteCommand>());
	}

	private void EndFrame()
	{
		for (var i = _spriteCount; i < _spritePool.Count; i++)
			_spritePool[i].Visible = false;
	}

	private Sprite2D AcquireSprite()
	{
		var idx = _spriteCount++;
		if (idx < _spritePool.Count) return _spritePool[idx];
		var sprite = new Sprite2D
		{
			Name = "VoxelSprite" + _spritePool.Count.ToString(),
			Centered = true,
			TextureFilter = CanvasItem.TextureFilterEnum.Nearest,
		};
		_root!.AddChild(sprite);
		_spritePool.Add(sprite);
		return sprite;
	}

	private void UpdateCamera(int cx, int cy, int cz)
	{
		if (_camera != null)
			_camera.Position = IsoCoordUtil.WorldToScreen(cx, cy, cz);
	}

	// ── Types ──

	private enum VoxelFace
	{
		Top,
		Left,
		Right,
	}

	public readonly record struct IsometricLightingSettings(
		float Ambient,
		float TopLight,
		float LeftLight,
		float RightLight,
		float DepthFalloff,
		float Contrast,
		float ShadowStrength,
		float OcclusionStep)
	{
		public IsometricLightingSettings Clamp(float minLight, float maxLight)
		{
			return new IsometricLightingSettings(
				Math.Clamp(Ambient, minLight, maxLight),
				Math.Clamp(TopLight, minLight, maxLight),
				Math.Clamp(LeftLight, minLight, maxLight),
				Math.Clamp(RightLight, minLight, maxLight),
				Math.Clamp(DepthFalloff, 0f, 0.35f),
				Math.Clamp(Contrast, 0.65f, 1.8f),
				Math.Clamp(ShadowStrength, 0f, 1.2f),
				Math.Clamp(OcclusionStep, 0f, 0.35f));
		}
	}

	private readonly record struct FaceSpriteCommand(
		Rect2 SourceRegion,
		Vector2 Position,
		Color Tint,
		long SortKey);

	private sealed partial class VoxelFaceBatchCanvas : Node2D
	{
		private FaceSpriteCommand[] _commands = Array.Empty<FaceSpriteCommand>();
		private Texture2D? _atlasTexture;

		public void SetAtlasTexture(Texture2D? atlas) => _atlasTexture = atlas;

		public void SetCommands(IReadOnlyList<FaceSpriteCommand> commands)
		{
			if (commands.Count == 0)
			{
				_commands = Array.Empty<FaceSpriteCommand>();
				QueueRedraw();
				return;
			}

			if (_commands.Length != commands.Count)
				_commands = new FaceSpriteCommand[commands.Count];

			for (var i = 0; i < commands.Count; i++)
				_commands[i] = commands[i];

			QueueRedraw();
		}

		public override void _Draw()
		{
			if (_atlasTexture == null)
				return;

			for (var i = 0; i < _commands.Length; i++)
			{
				var cmd = _commands[i];
				var size = cmd.SourceRegion.Size;
				if (size.X <= 0 || size.Y <= 0)
					continue;

				var destRect = new Rect2(cmd.Position - size / 2f, size);
				DrawTextureRectRegion(_atlasTexture, destRect, cmd.SourceRegion, cmd.Tint);
			}
		}
	}

	private struct VoxelDrawCommand
	{
		public int WorldX, WorldY, WorldZ;
		public Vector2 ScreenPos;
		public long SortKey;
		public TerrainDef Terrain;
		public bool DrawTop, DrawLeftSide, DrawRightSide;
		public bool ShadowTop;
	}

	private readonly record struct EntityDrawCommand(
		long SortKey,
		Vector2 ScreenPos,
		Actor? Actor,
		string Label,
		Color Tint);

	private readonly record struct HoverHighlightCommand(
		Vector2 ScreenPos,
		Color Tint,
		long SortKey);

	private readonly record struct ActorSpriteVisual(
		Texture2D Texture,
		Rect2? Region,
		Vector2 Scale,
		Vector2 Offset);

	private record struct CachedBlockTextures(Texture2D? Top, Texture2D? Left, Texture2D? Right);
}
