using System;
using System.Collections.Generic;
using System.Diagnostics;
using Godot;
using MiniRPG.Core.Config;
using MiniRPG.Core.Data;
using MiniRPG.Core.Health;
using MiniRPG.Core.Weather;
using MiniRPG.Core.World;
using MiniRPG.Module.Editor;
using MiniRPG.Module.WorldTool;

namespace MiniRPG.Module.Render;

/// <summary>
/// Isometric voxel renderer: renders multi-layer block world in 2.5D isometric view.
/// Each visible block draws top face (diamond) + left side + right side.
/// Side faces are programmatically generated by sampling the bottom edges of the top tile.
/// </summary>
public partial class IsometricVoxelRenderer
{
	private const int DefaultCharacterSheetFrameWidth = 128;
	private const int DefaultCharacterSheetFrameHeight = 128;
	private const float LeftDarken = 0.65f;
	private const float RightDarken = 0.80f;
	private const float WallTopEdgeStrength = 0.30f;
	private static readonly IsometricLightingSettings DefaultLighting = new(
		Ambient: 1.0f,
		TopLight: 1.0f,
		LeftLight: 0.72f,
		RightLight: 0.86f,
		DepthFalloff: 0.0f,
		Contrast: 1.0f,
		ShadowStrength: 0.0f,
		OcclusionStep: 0.0f);
	private const float MinLight = 0.12f;
	private const float MaxLight = 1.65f;
	private const float SolidTopEdgeStrength = 0.22f;
	private const float NonSolidTopEdgeStrength = 0.12f;
	private const float WallSideEdgeStrength = 0.20f;
	private const float SolidSideEdgeStrength = 0.12f;
	private const float NonSolidSideEdgeStrength = 0.06f;
	private const int SideTextureWidth = VoxelFaceImageUtil.SideTextureWidth;
	private const int SideTextureHeight = VoxelFaceImageUtil.SideTextureHeight;
	private const int SideFaceHeight = VoxelFaceImageUtil.SideFaceHeight;
	private const int WallSideFaceHeight = VoxelFaceImageUtil.WallSideFaceHeight;
	private const float DefaultLeftSideDarken = LeftDarken;
	private const float DefaultRightSideDarken = RightDarken;
	private const float WallLeftSideDarken = 0.52f;
	private const float WallRightSideDarken = 0.68f;
	private readonly GameState _state;
	private readonly FogOfWarTracker _fogTracker;
	private readonly int _viewW;
	private readonly int _viewH;

	private Node2D? _root;
	private Camera2D? _camera;
	private SubViewportContainer? _viewportContainer;
	private SubViewport? _subViewport;
	private WeatherFxController? _weatherFxController;
	private Node2D? _combatFxWorldRoot;
	private IAnimatable? _playerAnim;
	private Vector2? _editorCameraTarget;
	private MapEditorHoverState? _editorHoverState;
	private const float EditorCameraLerpSpeed = 14f;

	private readonly VoxelSpritePool _spritePool = new();
	private int _spriteCount;
	private VoxelFaceBatchCanvas? _faceBatchCanvas;
	private readonly List<FaceSpriteCommand> _faceCommands = [];
	private readonly List<VoxelDrawCommand> _drawCommands = [];
	private readonly List<EntityDrawCommand> _entityCommands = [];
	private readonly Dictionary<ChunkCoord, ChunkTerrainSurfaceCache> _terrainSurfaceCache = new();
	private readonly List<ChunkCoord> _terrainSurfaceCachePruneBuffer = [];
	private int _lastDrawCommandCount;

	private IsometricLightingSettings _lighting = DefaultLighting;

	private readonly LightMap _lightMap = new();
	private readonly VoxelLightingCalculator _lightingCalc;
	private readonly TerrainAtlas _terrainAtlas = new();

	// ── Orchestration state (formerly TileMapRenderModule) ──
	private float _zoom = 1.0f;
	private float _minCameraZoom = 0.6f;
	private float _maxCameraZoom = 2.4f;
	private const float CameraZoomStep = 0.1f;
	private bool _editorViewActive;
	private bool _runtimeViewActive;
	private RuntimeCameraSnapshot _runtimeCameraView = RuntimeCameraSnapshot.Create(RuntimeCameraMode.FollowActor, 0, 0, 0);
	private int _viewCenterX;
	private int _viewCenterY;
	private int _viewCenterZ;
	private double _tileAnimationClockSeconds;
	private int _lightingProfileIndex;
	private int _tileDrawCommandCount;
	private readonly RenderPerfTracer _perfTracer = new();
	private EditorPerspectiveResult _editorPerspective = EditorPerspectiveResult.Empty;
	private Vector2 _playerVisualCorrectionOffset = Vector2.Zero;
	private float _playerVisualCorrectionRemaining;
	private float _playerVisualCorrectionDuration;
	private readonly ActorMotionTracker _motionTracker = new();
	private RenderTraceSample _lastRenderTraceSample = RenderTraceSample.Empty;

	private static readonly (string Key, IsometricLightingSettings Lighting)[] LightingProfiles =
	[
		("render.lighting.profile.default", new IsometricLightingSettings(0.84f, 1.12f, 0.76f, 0.90f, 0.06f, 1.06f, 0.58f, 0.085f)),
		("render.lighting.profile.cinematic", new IsometricLightingSettings(0.72f, 1.24f, 0.62f, 0.95f, 0.09f, 1.18f, 0.76f, 0.11f)),
		("render.lighting.profile.soft", new IsometricLightingSettings(0.94f, 1.04f, 0.86f, 0.92f, 0.03f, 0.92f, 0.42f, 0.06f)),
	];

	private static readonly Dictionary<string, string> CharacterSheetMap = new(StringComparer.OrdinalIgnoreCase)
	{
		["Idle"] = "Idle",
		["Walk"] = "Walk",
		["Run"] = "Run",
		["Attack_1"] = "Attack1",
		["Attack1"] = "Attack1",
		["Pain"] = "TakeDamage",
		["TakeDamage"] = "TakeDamage",
		["Die"] = "Die",
		["Special_1"] = "Special1",
		["Special1"] = "Special1",
	};

	public IsometricVoxelRenderer(GameState state, FogOfWarTracker fogTracker, int viewW, int viewH)
	{
		_state = state;
		_fogTracker = fogTracker;
		_viewW = viewW;
		_viewH = viewH;
		_lightingCalc = new VoxelLightingCalculator(_lightMap);
	}

	public int LastSpriteCount => _spriteCount;
	public int LastDrawCommandCount => _lastDrawCommandCount;
	public IsometricLightingSettings LightingSettings => _lighting;
	internal MapEditorHoverState? EditorHoverState
	{
		get => _editorHoverState;
		set
		{
			_editorHoverState = value;
			WorldToolPreviewState = MapEditorWorldToolPreviewAdapter.FromMapEditorHoverState(value);
		}
	}
	internal WorldToolPreviewState? WorldToolPreviewState { get; set; }
	public Node2D CombatFxWorldRoot => _combatFxWorldRoot!;
	public bool IsIsometricMode => true;
	public int LightingProfileIndex => _lightingProfileIndex;
	public RenderPerfSnapshot LastPerfSnapshot => _perfTracer.LastPerfSnapshot;
	public float Zoom => _zoom;
	public bool FogMapVisible { get; set; }
	public bool MinimapVisible { get; set; }
	public Vector2I MapViewportSize => _subViewport?.Size ?? Vector2I.Zero;
	public Vector2 MapViewportContainerSize => _viewportContainer?.Size ?? Vector2.Zero;
	public bool IsRevealAll => _fogTracker.RevealAll;
	public IAnimatable? PlayerAnimatable => _playerAnim;
	public bool HasAnyActorMotion => _motionTracker.HasAny;
	public bool HasBlockingActorMotion => _motionTracker.HasBlocking;

	internal VisibleWorldWindow GetVisibleWorldWindow()
	{
		var fallback = new VisibleWorldWindow(_viewW / 2, _viewH / 2);
		if (_subViewport == null || _camera == null)
			return fallback;

		return VoxelViewportMath.CalculateVisibleWorldWindow(
			_subViewport.Size,
			_camera.Zoom,
			fallback);
	}

	internal VisibleDepthWindow GetVisibleDepthWindow(VisibleWorldWindow? visibleWorldWindow = null)
	{
		var fallback = new VisibleDepthWindow(VoxelViewportMath.DefaultViewDepthAbove, VoxelViewportMath.DefaultViewDepthBelow);
		if (_subViewport == null || _camera == null)
			return fallback;

		var resolvedVisibleWorldWindow = visibleWorldWindow ?? GetVisibleWorldWindow();
		return VoxelViewportMath.CalculateVisibleDepthWindow(
			_subViewport.Size,
			_camera.Zoom,
			resolvedVisibleWorldWindow,
			fallback);
	}

	private Rect2? GetVisibleMapRect()
	{
		if (_subViewport == null || _camera == null)
			return null;

		return VoxelViewportMath.CalculateVisibleMapRect(
			_subViewport.Size,
			_camera.Position,
			_camera.Zoom);
	}

	public static IReadOnlyList<string> EnumerateWeatherAssetPaths() =>
		WeatherFxController.EnumerateWeatherAssetPaths();

	public void Init(
		Node2D mapRoot,
		TileSet tileSet,
		SubViewportContainer? viewportContainer,
		SubViewport? subViewport,
		Node2D? playerVisual,
		Camera2D? camera)
	{
		_viewportContainer = viewportContainer;
		_subViewport = subViewport;
		_camera = camera;

		if (playerVisual != null)
		{
			playerVisual.Visible = false;
			_playerAnim = playerVisual as IAnimatable ?? new TileAnimatable(playerVisual);
			ResAccess.RegisterAnimatable("player", _playerAnim);
			if (!string.IsNullOrWhiteSpace(_state.PlayerId))
				ResAccess.RegisterAnimatable(_state.PlayerId, _playerAnim);
		}

		var voxelRoot = new Node2D { Name = "VoxelRoot", Visible = true };
		mapRoot.AddChild(voxelRoot);
		_root = voxelRoot;

		_combatFxWorldRoot = new Node2D { Name = "CombatFxWorldRoot", ZIndex = 6 };
		mapRoot.AddChild(_combatFxWorldRoot);

		_terrainAtlas.Build();

		_faceBatchCanvas?.QueueFree();
		_faceBatchCanvas = new VoxelFaceBatchCanvas
		{
			Name = "VoxelFaceBatchCanvas",
			ZIndex = 0,
		};
		_faceBatchCanvas.SetAtlasTexture(_terrainAtlas.AtlasTexture);
		_root.AddChild(_faceBatchCanvas);

		_weatherFxController = new WeatherFxController(_state);
		var weatherOverlayRoot = new Node2D { Name = "WeatherOverlayRoot", ZIndex = 1, Visible = false };
		mapRoot.AddChild(weatherOverlayRoot);
		var peripheralWeatherOverlayRoot = new Node2D { Name = "PeripheralWeatherOverlayRoot", ZIndex = 1, Visible = false };
		mapRoot.AddChild(peripheralWeatherOverlayRoot);
		var memoryWeatherOverlayRoot = new Node2D { Name = "MemoryWeatherOverlayRoot", ZIndex = 1, Visible = false };
		mapRoot.AddChild(memoryWeatherOverlayRoot);
		var weatherFxRoot = new Node2D { Name = "WeatherFxRoot", ZIndex = 2, Visible = false };
		mapRoot.AddChild(weatherFxRoot);
		var peripheralWeatherFxRoot = new Node2D { Name = "PeripheralWeatherFxRoot", ZIndex = 2, Visible = false };
		mapRoot.AddChild(peripheralWeatherFxRoot);
		_weatherFxController.Init(
			mapRoot, static _ => Vector2.Zero, new Vector2(64f, 64f), viewportContainer,
			weatherOverlayRoot, peripheralWeatherOverlayRoot, memoryWeatherOverlayRoot,
			weatherFxRoot, peripheralWeatherFxRoot);

		ApplyLightingProfile(_lightingProfileIndex);
		UpdateCameraZoom();
	}

	public void ConfigureLighting(IsometricLightingSettings? settings = null)
	{
		var resolved = settings ?? DefaultLighting;
		if (_lighting.Equals(resolved))
			return;

		_lighting = resolved.Clamp(MinLight, MaxLight);
	}

	// ── Orchestration (Flush / Advance / Coordinate Picking / Zoom) ──

	public void SetEditorView(bool active, int centerX, int centerY, int centerZ)
	{
		_editorViewActive = active;
		_viewCenterX = centerX;
		_viewCenterY = centerY;
		_viewCenterZ = centerZ;
	}

	internal void SetRuntimeView(bool active, RuntimeCameraSnapshot snapshot)
	{
		_runtimeViewActive = active;
		if (!active)
			return;

		_runtimeCameraView = snapshot;
		_viewCenterX = snapshot.CenterX;
		_viewCenterY = snapshot.CenterY;
		_viewCenterZ = snapshot.CenterZ;
	}

	internal static Vector3I? ResolveHoverHighlightCell(
		Vector3I? hoverWorldCell,
		WorldToolPreviewState? previewState) =>
		WorldToolPreviewHelper.ResolveHoverHighlightCell(hoverWorldCell, previewState);

	internal static Vector3I? ResolveHoverHighlightCell(
		bool editorViewActive,
		Vector3I? hoverWorldCell,
		MapEditorHoverState? editorHoverState) =>
		WorldToolPreviewHelper.ResolveHoverHighlightCell(editorViewActive, hoverWorldCell, editorHoverState);

	internal static bool ShouldDrawPlacementGhost(WorldToolPreviewState? hoverState) =>
		WorldToolPreviewHelper.ShouldDrawPlacementGhost(hoverState);

	internal static bool ShouldDrawEditorPlacementGhost(MapEditorHoverState? hoverState) =>
		WorldToolPreviewHelper.ShouldDrawEditorPlacementGhost(hoverState);

	internal static bool ShouldHidePreviewTerrain(WorldToolPreviewState? hoverState, int worldX, int worldY, int worldZ) =>
		WorldToolPreviewHelper.ShouldHidePreviewTerrain(hoverState, worldX, worldY, worldZ);

	internal static bool ShouldHideEditorPreviewTerrain(MapEditorHoverState? hoverState, int worldX, int worldY, int worldZ) =>
		WorldToolPreviewHelper.ShouldHideEditorPreviewTerrain(hoverState, worldX, worldY, worldZ);

	internal static bool ShouldHidePreviewFixture(WorldToolPreviewState? hoverState, int worldX, int worldY, int worldZ, string entityId) =>
		WorldToolPreviewHelper.ShouldHidePreviewFixture(hoverState, worldX, worldY, worldZ, entityId);

	internal static bool ShouldHideEditorPreviewFixture(MapEditorHoverState? hoverState, int worldX, int worldY, int worldZ, string entityId) =>
		WorldToolPreviewHelper.ShouldHideEditorPreviewFixture(hoverState, worldX, worldY, worldZ, entityId);

	internal static bool ShouldHidePreviewFacility(WorldToolPreviewState? hoverState, string facilityId) =>
		WorldToolPreviewHelper.ShouldHidePreviewFacility(hoverState, facilityId);

	internal static int GetPlacementGhostCommandCount(WorldToolPreviewState? hoverState) =>
		WorldToolPreviewHelper.GetPlacementGhostCommandCount(hoverState);

	internal static int GetEditorPlacementGhostCommandCount(MapEditorHoverState? hoverState) =>
		WorldToolPreviewHelper.GetEditorPlacementGhostCommandCount(hoverState);

	internal void SetWeatherScreenFxTuning(WeatherScreenFxTuningSet? tuning)
		=> _weatherFxController?.SetTuning(tuning, _editorViewActive);

	internal void PresentActorMotion(ActorMotionPresentationRequest request)
	{
		if (string.IsNullOrWhiteSpace(request.ActorId))
			return;

		if (!ShouldAnimateActorMotion(request))
		{
			ClearActorMotion(request.ActorId);
			return;
		}

		_motionTracker.Record(
			request.ActorId,
			request.SourceX,
			request.SourceY,
			request.SourceZ,
			request.TargetX,
			request.TargetY,
			request.TargetZ,
			_tileAnimationClockSeconds,
			request.DurationSecondsOverride ?? ActorMotionTiming.ResolveDurationSeconds(request.TimingTier),
			request.Blocking);
	}

	internal void ClearActorMotion(string actorId)
	{
		_motionTracker.Remove(actorId);
	}

	internal void ResetActorMotionState()
	{
		_motionTracker.Clear();
	}

	internal Vector3 ResolveActorVisualWorldPosition(string actorId)
	{
		var actor = ActorModule.GetById(_state, actorId);
		return actor == null ? Vector3.Zero : ResolveActorVisualWorldPosition(actor);
	}

	internal Vector2 ResolveRuntimeCameraScreenTarget() =>
		ResolveRuntimeCameraTarget(_viewCenterX, _viewCenterY, _viewCenterZ);

	public void Flush()
	{
		var frameStartUsec = Time.GetTicksUsec();
		_tileDrawCommandCount = 0;
		_weatherFxController?.BeginFrame();

		if (_state.World == null)
		{
			ResetActorMotionState();
			_weatherFxController?.ClearScreenFxTarget();
			_weatherFxController?.UpdateWeatherScreenFxOverlay(0d, _tileAnimationClockSeconds);
			_weatherFxController?.EndFrame();
			CommitPerfFrame((Time.GetTicksUsec() - frameStartUsec) / 1000.0);
			return;
		}

		if (_editorViewActive)
		{
			_fogTracker.RevealAll = true;
			_weatherFxController?.ClearScreenFxTarget();
		}
		else
		{
			_fogTracker.RevealAll = false;
			_fogTracker.Update(_state);
			_weatherFxController?.RefreshWeatherScreenFxTarget(editorViewActive: false);
			if (!_runtimeViewActive)
			{
				_viewCenterX = _state.PlayerX;
				_viewCenterY = _state.PlayerY;
				_viewCenterZ = _state.PlayerZ;
				_runtimeCameraView = RuntimeCameraSnapshot.Create(
					RuntimeCameraMode.FollowActor,
					_viewCenterX,
					_viewCenterY,
					_viewCenterZ);
			}
		}

		Render();
		_tileDrawCommandCount = _lastDrawCommandCount;
		_weatherFxController?.UpdateWeatherScreenFxOverlay(0d, _tileAnimationClockSeconds);
		_weatherFxController?.EndFrame();
		_motionTracker.Prune(_tileAnimationClockSeconds);
		CommitPerfFrame((Time.GetTicksUsec() - frameStartUsec) / 1000.0);
	}

	public void AdvanceAnimations(double delta)
	{
		if (delta <= 0d) return;
		_tileAnimationClockSeconds += delta;
		_weatherFxController?.UpdateWeatherScreenFxOverlay(delta, _tileAnimationClockSeconds);
		AdvancePlayerCorrectionSmoothing((float)delta);
		_motionTracker.UpdateBlockingFlag(_tileAnimationClockSeconds);
		AdvanceEditorCameraSmoothing((float)delta);
	}

	private bool ShouldAnimateActorMotion(ActorMotionPresentationRequest request)
	{
		if (!ActorMotionTracker.IsStandardStep(request))
			return false;

		if (string.Equals(request.ActorId, PartyModule.GetActiveId(_state), StringComparison.Ordinal))
			return true;

		return IsActorMotionRenderable(request.SourceX, request.SourceY, request.SourceZ)
			|| IsActorMotionRenderable(request.TargetX, request.TargetY, request.TargetZ);
	}

	private bool IsActorMotionRenderable(int worldX, int worldY, int worldZ)
	{
		var visibleWindow = GetVisibleWorldWindow();
		var visibleDepth = GetVisibleDepthWindow(visibleWindow);
		var zMin = _viewCenterZ - visibleDepth.Above;
		var zMax = _viewCenterZ + visibleDepth.Below;
		return Math.Abs(worldX - _viewCenterX) <= visibleWindow.HalfX + 1
			&& Math.Abs(worldY - _viewCenterY) <= visibleWindow.HalfY + 1
			&& worldZ >= zMin
			&& worldZ <= zMax
			&& _fogTracker.GetVisionBand(worldX, worldY, worldZ) != PlayerVisionBand.Unknown;
	}

	private Vector3 ResolveActorVisualWorldPosition(Actor actor)
	{
		return _motionTracker.TryGetInterpolatedPosition(actor.Id, _tileAnimationClockSeconds, out var position)
			? position
			: new Vector3(actor.X, actor.Y, actor.Z);
	}

	private void AdvanceEditorCameraSmoothing(float delta)
	{
		if (_camera == null || _editorCameraTarget is not { } target)
			return;

		var current = _camera.Position;
		if (current.DistanceSquaredTo(target) < 0.5f)
		{
			_camera.Position = target;
			return;
		}

		_camera.Position = current.Lerp(target, Mathf.Clamp(EditorCameraLerpSpeed * delta, 0f, 1f));
	}

	public bool IsWorldCellVisible(int wx, int wy, int wz)
	{
		if (_state.World == null) return false;
		var band = _fogTracker.GetVisionBand(wx, wy, wz);
		return band is PlayerVisionBand.Focused or PlayerVisionBand.Peripheral;
	}

	public bool TryGetWorldCellFromGlobalPosition(Vector2 globalPos, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (!TryGetMapLocalFromGlobalPosition(globalPos, out var mapLocal))
			return false;

		return TryPickIsometricCell(mapLocal, out worldCell);
	}

	public bool TryGetInspectWorldCellFromGlobalPosition(Vector2 globalPos, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (!TryGetMapLocalFromGlobalPosition(globalPos, out var mapLocal))
			return false;

		return TryPickInspectCell(mapLocal, out worldCell);
	}

	public bool TryGetEditorWorldCellFromGlobalPosition(Vector2 globalPos, int targetZ, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (!TryGetMapLocalFromGlobalPosition(globalPos, out var mapLocal))
			return false;

		return TryPickEditorCell(mapLocal, targetZ, out worldCell);
	}

	private bool TryGetMapLocalFromGlobalPosition(Vector2 globalPos, out Vector2 mapLocal)
	{
		mapLocal = Vector2.Zero;
		if (_viewportContainer == null || _subViewport == null || _camera == null)
			return false;

		var rect = _viewportContainer.GetGlobalRect();
		if (!rect.HasPoint(globalPos) || rect.Size.X <= 0 || rect.Size.Y <= 0)
			return false;

		var localInContainer = globalPos - rect.Position;
		var viewportPos = new Vector2(
			localInContainer.X * _subViewport.Size.X / rect.Size.X,
			localInContainer.Y * _subViewport.Size.Y / rect.Size.Y);
		var viewportSize = new Vector2(_subViewport.Size.X, _subViewport.Size.Y);
		var screenOffset = viewportPos - viewportSize / 2f;
		mapLocal = ResolveMapCameraPosition() + new Vector2(
			screenOffset.X / _camera.Zoom.X,
			screenOffset.Y / _camera.Zoom.Y);
		return true;
	}

	public bool TryGetMapLocalDeltaFromGlobalMotion(Vector2 globalMotion, out Vector2 mapLocalDelta)
	{
		mapLocalDelta = Vector2.Zero;
		if (_viewportContainer == null || _subViewport == null || _camera == null)
			return false;

		var rect = _viewportContainer.GetGlobalRect();
		if (rect.Size.X <= 0f || rect.Size.Y <= 0f || _camera.Zoom.X == 0f || _camera.Zoom.Y == 0f)
			return false;

		mapLocalDelta = new Vector2(
			globalMotion.X * _subViewport.Size.X / rect.Size.X / _camera.Zoom.X,
			globalMotion.Y * _subViewport.Size.Y / rect.Size.Y / _camera.Zoom.Y);
		return true;
	}

	private Vector2 ResolveMapCameraPosition()
	{
		if (_editorViewActive && _camera != null)
			return _camera.Position;
		if (_runtimeViewActive)
			return ResolveRuntimeCameraScreenTarget();
		return _camera?.Position ?? Vector2.Zero;
	}

	private bool TryPickIsometricCell(Vector2 screenPos, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (_state.World == null) return false;

		if (_runtimeViewActive)
		{
			var (runtimeX, runtimeY) = IsoCoordUtil.ScreenToWorldCell(screenPos, _runtimeCameraView.CenterZ);
			worldCell = new Vector3I(runtimeX, runtimeY, _runtimeCameraView.CenterZ);
			return true;
		}

		var cz = _editorViewActive ? _viewCenterZ : _state.PlayerZ;
		var visibleDepth = GetVisibleDepthWindow();
		var zMin = cz - visibleDepth.Above;
		var zMax = cz + visibleDepth.Below;
		for (var z = zMax; z >= zMin; z--)
		{
			var (wx, wy) = IsoCoordUtil.ScreenToWorldCell(screenPos, z);
			var terrain = _state.World.GetTerrain(wx, wy, z);
			if (terrain.StringId != Terrains.Air && terrain.StringId != Terrains.Void)
			{
				worldCell = new Vector3I(wx, wy, z);
				return true;
			}
		}

		// Editor mode: allow targeting empty cells at camera Z for block placement
		if (_editorViewActive)
		{
			var (fallbackX, fallbackY) = IsoCoordUtil.ScreenToWorldCell(screenPos, cz);
			worldCell = new Vector3I(fallbackX, fallbackY, cz);
			return true;
		}

		return false;
	}

	private bool TryPickEditorCell(Vector2 screenPos, int targetZ, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (_state.World == null)
			return false;

		var (wx, wy) = IsoCoordUtil.ScreenToWorldCell(screenPos, targetZ);
		worldCell = new Vector3I(wx, wy, targetZ);
		return true;
	}

	private bool TryPickInspectCell(Vector2 screenPos, out Vector3I worldCell)
	{
		worldCell = Vector3I.Zero;
		if (_state.World == null)
			return false;

		if (!_runtimeViewActive)
			return TryPickIsometricCell(screenPos, out worldCell);

		var visibleWindow = GetVisibleWorldWindow();
		var visibleDepth = GetVisibleDepthWindow(visibleWindow);
		var zMin = _runtimeCameraView.CenterZ - visibleDepth.Below;
		var zMax = _runtimeCameraView.CenterZ + visibleDepth.Above;
		Vector3I? bestNonEmptyCell = null;
		for (var z = zMax; z >= zMin; z--)
		{
			var (wx, wy) = IsoCoordUtil.ScreenToWorldCell(screenPos, z);
			if (!IsWorldCellVisible(wx, wy, z))
				continue;

			var cell = new Vector3I(wx, wy, z);
			if (ActorModule.GetAllAt(_state, wx, wy, z).Count > 0)
			{
				worldCell = cell;
				return true;
			}

			var items = _state.World.PeekGroundItems(wx, wy, z);
			if (items.Exists(static item => item.IsCorpse))
			{
				worldCell = cell;
				return true;
			}

			if (bestNonEmptyCell == null && HasInspectableCellContent(wx, wy, z))
				bestNonEmptyCell = cell;
		}

		if (bestNonEmptyCell is { } resolvedCell)
		{
			worldCell = resolvedCell;
			return true;
		}

		var (fallbackX, fallbackY) = IsoCoordUtil.ScreenToWorldCell(screenPos, _runtimeCameraView.CenterZ);
		worldCell = new Vector3I(fallbackX, fallbackY, _runtimeCameraView.CenterZ);
		return true;
	}

	private bool HasInspectableCellContent(int wx, int wy, int wz)
	{
		if (_state.World == null)
			return false;

		var terrain = _state.World.GetTerrain(wx, wy, wz).StringId;
		if (terrain is not (Terrains.Air or Terrains.Void))
			return true;
		if (!string.IsNullOrWhiteSpace(_state.World.GetFixtureId(wx, wy, wz)))
			return true;
		if (_state.World.GetEntities(wx, wy, wz).Count > 0)
			return true;
		if (FireSystem.GetFireIntensityAt(_state, wx, wy, wz) > 0)
			return true;

		return false;
	}

	public bool TryGetWorldEffectPosition(int wx, int wy, int wz, out Vector2 position)
	{
		position = IsoCoordUtil.WorldToScreen(wx, wy, wz);
		return true;
	}

	public bool TryGetWorldOverlayPosition(int wx, int wy, int wz, out Vector2 position)
	{
		position = Vector2.Zero;
		var mapPos = IsoCoordUtil.WorldToScreen(wx, wy, wz);
		return TryMapToOverlayPosition(mapPos, out position);
	}

	private bool TryMapToOverlayPosition(Vector2 mapPosition, out Vector2 overlayPosition)
	{
		overlayPosition = Vector2.Zero;
		if (_camera == null || _subViewport == null || _viewportContainer == null)
			return false;

		var viewportSize = new Vector2(_subViewport.Size.X, _subViewport.Size.Y);
		if (viewportSize.X <= 0f || viewportSize.Y <= 0f)
			return false;

		var zoom = _camera.Zoom;
		var viewportPosition = viewportSize / 2f + new Vector2(
			(mapPosition.X - _camera.Position.X) * zoom.X,
			(mapPosition.Y - _camera.Position.Y) * zoom.Y);
		var containerSize = _viewportContainer.Size;
		if (containerSize.X <= 0f || containerSize.Y <= 0f)
			return false;

		overlayPosition = new Vector2(
			viewportPosition.X * containerSize.X / viewportSize.X,
			viewportPosition.Y * containerSize.Y / viewportSize.Y);
		return true;
	}

	public bool StepZoom(int direction)
	{
		if (_camera == null || direction == 0)
			return false;
		var requestedZoom = Mathf.Clamp(_zoom + direction * CameraZoomStep, _minCameraZoom, _maxCameraZoom);
		if (Mathf.IsEqualApprox(requestedZoom, _zoom))
			return false;
		_zoom = requestedZoom;
		UpdateCameraZoom();
		return true;
	}

	public void SetZoomRange(float minZoom, float maxZoom)
	{
		var normalizedMin = Mathf.Clamp(minZoom, 0.2f, 4.0f);
		var normalizedMax = Mathf.Clamp(maxZoom, 0.2f, 4.0f);
		if (normalizedMin > normalizedMax)
			(normalizedMin, normalizedMax) = (normalizedMax, normalizedMin);
		_minCameraZoom = normalizedMin;
		_maxCameraZoom = normalizedMax;
		_zoom = Mathf.Clamp(_zoom, _minCameraZoom, _maxCameraZoom);
		UpdateCameraZoom();
	}

	public bool SetZoomTo(float zoom)
	{
		if (_camera == null) return false;
		var clamped = Mathf.Clamp(zoom, _minCameraZoom, _maxCameraZoom);
		if (Mathf.IsEqualApprox(clamped, _zoom)) return false;
		_zoom = clamped;
		UpdateCameraZoom();
		return true;
	}

	private void UpdateCameraZoom()
	{
		if (_camera != null)
			_camera.Zoom = Vector2.One * _zoom;
	}

	public string? ToggleRenderMode()
		=> LocalizationService.T("render.view_mode.iso_only");

	public string CycleIsometricLightingProfile()
	{
		if (LightingProfiles.Length == 0)
			return LocalizationService.TOrFallback("render.lighting.unavailable", "Lighting profile is unavailable.");

		_lightingProfileIndex = (_lightingProfileIndex + 1) % LightingProfiles.Length;
		ApplyLightingProfile(_lightingProfileIndex);
		var profileKey = LightingProfiles[_lightingProfileIndex].Key;
		return LocalizationService.TOrFallback(
			"render.lighting.profile_changed",
			"Lighting profile switched: {profile}",
			("profile", LocalizationService.TOrFallback(profileKey, profileKey)));
	}

	public void SetLightingProfile(int profileIndex)
	{
		if (LightingProfiles.Length == 0) return;
		var clamped = Math.Clamp(profileIndex, 0, LightingProfiles.Length - 1);
		_lightingProfileIndex = clamped;
		ConfigureLighting(LightingProfiles[clamped].Lighting);
	}

	private void ApplyLightingProfile(int profileIndex) => SetLightingProfile(profileIndex);

	public string ToggleMinimap()
	{
		MinimapVisible = !MinimapVisible;
		return MinimapVisible
			? LocalizationService.T("render.minimap.unimplemented")
			: LocalizationService.T("render.minimap.closed");
	}

	public string ToggleFogMap()
	{
		FogMapVisible = !FogMapVisible;
		return FogMapVisible
			? LocalizationService.T("render.fog_map.unimplemented")
			: LocalizationService.T("render.fog_map.closed");
	}

	public bool ToggleRevealAll()
	{
		_fogTracker.RevealAll = !_fogTracker.RevealAll;
		return _fogTracker.RevealAll;
	}

	public void CenterFogMap() { }
	public void ScrollFogMap(int dx, int dy) { }
	public void ResetOverlays() { FogMapVisible = false; MinimapVisible = false; }

	public void PlaySpineAnim(string animName, bool loop, int track = 0)
		=> _playerAnim?.Play(animName, loop);

	public void QueueSpineAnim(string animName, bool loop, float delay = 0f, int track = 0) { }

	public void PlayOneShotThenIdle(string animName)
		=> _playerAnim?.PlayOneShot(animName, "Idle");

	public void ApplyPlayerCorrectionSmoothing(Vector2 worldCellOffset, float durationSeconds)
	{
		_playerVisualCorrectionOffset = worldCellOffset * new Vector2(64f, 64f);
		_playerVisualCorrectionDuration = Math.Max(0.001f, durationSeconds);
		_playerVisualCorrectionRemaining = _playerVisualCorrectionDuration;
	}

	private void AdvancePlayerCorrectionSmoothing(float deltaSeconds)
	{
		if (_playerVisualCorrectionRemaining <= 0f) return;
		_playerVisualCorrectionRemaining = Math.Max(0f, _playerVisualCorrectionRemaining - deltaSeconds);
		var ratio = _playerVisualCorrectionDuration <= 0f
			? 0f : _playerVisualCorrectionRemaining / _playerVisualCorrectionDuration;
		_playerVisualCorrectionOffset *= ratio;
		if (_playerVisualCorrectionRemaining <= 0f)
			_playerVisualCorrectionOffset = Vector2.Zero;
	}

	private void CommitPerfFrame(double frameTimeMs)
	{
		_perfTracer.CommitPerfFrame(frameTimeMs, _spriteCount, _weatherFxController?.ActiveSpriteCount ?? 0, _tileDrawCommandCount, _editorViewActive, _lastRenderTraceSample);
	}

	public readonly record struct RenderPerfSnapshot(
		int ActiveSpriteCount,
		int DrawCommandCount,
		double FrameTimeAvgMs)
	{
		public static RenderPerfSnapshot Empty => new(0, 0, 0d);
	}

	public readonly record struct RenderTraceSample(
		double TerrainMs,
		double LightMapMs,
		double EntityMs,
		double HoverMs,
		double SceneMs,
		long ScannedTerrainCells,
		long PreviewHiddenTerrainCells,
		long ScreenCulledTerrainCells,
		long EmptyTerrainCells,
		long OccludedTerrainCells,
		long HiddenFaceTerrainCells,
		int AcceptedVoxelCount,
		int EntityCommandCount,
		int HighlightCommandCount,
		int FaceCommandCount)
	{
		public static RenderTraceSample Empty => new(
			0d,
			0d,
			0d,
			0d,
			0d,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0);
	}

	private static double GetElapsedMs(long startTimestamp) =>
		(Stopwatch.GetTimestamp() - startTimestamp) * 1000d / Stopwatch.Frequency;

	// ── Main Render Pass ──

	public void Render()
	{
		if (_state.World == null || _root == null)
		{
			_lastRenderTraceSample = RenderTraceSample.Empty;
			return;
		}

		var dayNight = DayNightCycle.Compute(_state.Turn);
		_lightingCalc.Configure(_lighting, dayNight);
		BeginFrame();

		var cx = _viewCenterX;
		var cy = _viewCenterY;
		var cz = _viewCenterZ;
		var visibleWindow = GetVisibleWorldWindow();
		var visibleDepth = GetVisibleDepthWindow(visibleWindow);
		var visibleMapRect = GetVisibleMapRect();
		var halfW = visibleWindow.HalfX;
		var halfH = visibleWindow.HalfY;
		var zMin = cz - visibleDepth.Above;
		var zMax = cz + visibleDepth.Below;
		var previewState = WorldToolPreviewState;
		var highlightCell = ResolveHoverHighlightCell(HoverWorldCell, previewState);
		_editorPerspective = _editorViewActive
			? EditorPerspectiveResolver.Resolve(
				_state,
				cx,
				cy,
				cz,
				zMin,
				zMax,
				highlightCell is { } hover ? new WorldCoord(hover.X, hover.Y, cz) : null)
			: EditorPerspectiveResult.Empty;

		_drawCommands.Clear();
		var terrainStageStart = Stopwatch.GetTimestamp();
		long scannedTerrainCells = 0;
		long previewHiddenTerrainCells = 0;
		long screenCulledTerrainCells = 0;
		long emptyTerrainCells = 0;
		long occludedTerrainCells = 0;
		long hiddenFaceTerrainCells = 0;
		CollectTerrainDrawCommands(
			_state.World,
			cx,
			cy,
			halfW,
			halfH,
			zMin,
			zMax,
			visibleMapRect,
			previewState,
			ref scannedTerrainCells,
			ref previewHiddenTerrainCells,
			ref screenCulledTerrainCells,
			ref emptyTerrainCells,
			ref occludedTerrainCells,
			ref hiddenFaceTerrainCells);

		_drawCommands.Sort(CompareVoxelDrawCommands);
		var terrainStageMs = GetElapsedMs(terrainStageStart);

		var lightMapStageStart = Stopwatch.GetTimestamp();
		_lightMap.Rebuild(_state.World, cx, cy, cz, halfW, halfH, zMin, zMax);
		var lightMapStageMs = GetElapsedMs(lightMapStageStart);

		var entityStageStart = Stopwatch.GetTimestamp();
		CollectEntityCommands(cx, cy, cz, halfW, halfH, zMin, zMax);
		var entityStageMs = GetElapsedMs(entityStageStart);

		var hoverStageStart = Stopwatch.GetTimestamp();
		CollectHoverHighlights(cx, cy, cz, halfW, halfH, zMin, zMax, visibleMapRect, previewState);
		var hoverStageMs = GetElapsedMs(hoverStageStart);
		_lastDrawCommandCount = _drawCommands.Count + _entityCommands.Count + _highlightCommandCount;

		var sceneStageStart = Stopwatch.GetTimestamp();
		RenderScene();
		var sceneStageMs = GetElapsedMs(sceneStageStart);
		_lastRenderTraceSample = new RenderTraceSample(
			terrainStageMs,
			lightMapStageMs,
			entityStageMs,
			hoverStageMs,
			sceneStageMs,
			scannedTerrainCells,
			previewHiddenTerrainCells,
			screenCulledTerrainCells,
			emptyTerrainCells,
			occludedTerrainCells,
			hiddenFaceTerrainCells,
			_drawCommands.Count,
			_entityCommands.Count,
			_highlightCommandCount,
			_faceCommands.Count);
		EndFrame();
		UpdateCamera(cx, cy, cz);
	}

	private void CollectTerrainDrawCommands(
		WorldMap world,
		int centerX,
		int centerY,
		int halfW,
		int halfH,
		int zMin,
		int zMax,
		Rect2? visibleMapRect,
		WorldToolPreviewState? previewState,
		ref long scannedTerrainCells,
		ref long previewHiddenTerrainCells,
		ref long screenCulledTerrainCells,
		ref long emptyTerrainCells,
		ref long occludedTerrainCells,
		ref long hiddenFaceTerrainCells)
	{
		var minX = centerX - halfW;
		var maxX = centerX + halfW;
		var minY = centerY - halfH;
		var maxY = centerY + halfH;

		for (var wz = zMin; wz <= zMax; wz++)
		{
			var minChunk = CoordUtil.WorldToChunk(minX, minY, wz);
			var maxChunk = CoordUtil.WorldToChunk(maxX, maxY, wz);
			for (var chunkY = minChunk.Cy; chunkY <= maxChunk.Cy; chunkY++)
			for (var chunkX = minChunk.Cx; chunkX <= maxChunk.Cx; chunkX++)
			{
				var chunk = world.Chunks.GetOrLoad(new ChunkCoord(chunkX, chunkY, wz));
				var cache = GetOrBuildChunkTerrainSurfaceCache(world, chunk, out var rebuiltThisFrame);
				if (rebuiltThisFrame)
				{
					emptyTerrainCells += cache.EmptyCellCount;
					occludedTerrainCells += cache.OccludedCellCount;
					hiddenFaceTerrainCells += cache.HiddenFaceCellCount;
				}

				for (var i = 0; i < cache.Entries.Length; i++)
				{
					var entry = cache.Entries[i];
					if (entry.WorldX < minX || entry.WorldX > maxX || entry.WorldY < minY || entry.WorldY > maxY)
						continue;

					scannedTerrainCells++;

					if (ShouldHidePreviewTerrain(previewState, entry.WorldX, entry.WorldY, entry.WorldZ))
					{
						previewHiddenTerrainCells++;
						continue;
					}

					if (visibleMapRect is { } mapRect && !VoxelViewportMath.IsVoxelScreenVisible(entry.ScreenPos, mapRect))
					{
						screenCulledTerrainCells++;
						continue;
					}

					_drawCommands.Add(new VoxelDrawCommand
					{
						WorldX = entry.WorldX,
						WorldY = entry.WorldY,
						WorldZ = entry.WorldZ,
						ScreenPos = entry.ScreenPos,
						SortKey = entry.SortKey,
						Terrain = entry.Terrain,
						DrawTop = entry.DrawTop,
						DrawLeftSide = entry.DrawLeftSide,
						DrawRightSide = entry.DrawRightSide,
						ShadowTop = entry.ShadowTop,
					});
				}
			}
		}

		PruneTerrainSurfaceCache(world.Chunks.LoadedChunks);
	}

	private ChunkTerrainSurfaceCache GetOrBuildChunkTerrainSurfaceCache(WorldMap world, ChunkData chunk, out bool rebuiltThisFrame)
	{
		if (_terrainSurfaceCache.TryGetValue(chunk.Coord, out var cache)
			&& cache.TerrainGeometryRevision == chunk.TerrainGeometryRevision)
		{
			rebuiltThisFrame = false;
			return cache;
		}

		var rebuilt = BuildChunkTerrainSurfaceCache(world, chunk);
		_terrainSurfaceCache[chunk.Coord] = rebuilt;
		rebuiltThisFrame = true;
		return rebuilt;
	}

	private void PruneTerrainSurfaceCache(IReadOnlyDictionary<ChunkCoord, ChunkData> loadedChunks)
	{
		_terrainSurfaceCachePruneBuffer.Clear();
		foreach (var coord in _terrainSurfaceCache.Keys)
		{
			if (!loadedChunks.ContainsKey(coord))
				_terrainSurfaceCachePruneBuffer.Add(coord);
		}

		for (var i = 0; i < _terrainSurfaceCachePruneBuffer.Count; i++)
			_terrainSurfaceCache.Remove(_terrainSurfaceCachePruneBuffer[i]);
	}

	private static ChunkTerrainSurfaceCache BuildChunkTerrainSurfaceCache(WorldMap world, ChunkData chunk)
	{
		var entries = BuildChunkTerrainSurfaceEntries(
			world,
			chunk,
			out var emptyCellCount,
			out var occludedCellCount,
			out var hiddenFaceCellCount);
		return new ChunkTerrainSurfaceCache(
			chunk.TerrainGeometryRevision,
			entries,
			emptyCellCount,
			occludedCellCount,
			hiddenFaceCellCount);
	}

	internal static TerrainSurfaceEntry[] BuildChunkTerrainSurfaceEntries(
		WorldMap world,
		ChunkData chunk,
		out int emptyCellCount,
		out int occludedCellCount,
		out int hiddenFaceCellCount)
	{
		var airId = TerrainRegistry.GetId(Terrains.Air);
		var voidId = TerrainRegistry.GetId(Terrains.Void);
		var baseX = chunk.Coord.Cx * ChunkData.Size;
		var baseY = chunk.Coord.Cy * ChunkData.Size;
		var entries = new List<TerrainSurfaceEntry>(ChunkData.Area);
		ChunkData? aboveChunk = null;
		ChunkData? eastChunk = null;
		ChunkData? southChunk = null;
		var neighborsResolved = false;

		emptyCellCount = 0;
		occludedCellCount = 0;
		hiddenFaceCellCount = 0;

		for (var ly = 0; ly < ChunkData.Size; ly++)
		for (var lx = 0; lx < ChunkData.Size; lx++)
		{
			var index = CoordUtil.LocalIndex(lx, ly);
			var terrainId = chunk.TerrainIds[index];
			if (terrainId == airId || terrainId == voidId)
			{
				emptyCellCount++;
				continue;
			}

			if (!neighborsResolved)
			{
				aboveChunk = world.Chunks.GetOrLoad(new ChunkCoord(chunk.Coord.Cx, chunk.Coord.Cy, chunk.Coord.Cz - 1));
				eastChunk = world.Chunks.GetOrLoad(new ChunkCoord(chunk.Coord.Cx + 1, chunk.Coord.Cy, chunk.Coord.Cz));
				southChunk = world.Chunks.GetOrLoad(new ChunkCoord(chunk.Coord.Cx, chunk.Coord.Cy + 1, chunk.Coord.Cz));
				neighborsResolved = true;
			}

			var topOpaque = IsChunkTerrainOpaque(aboveChunk!, lx, ly);
			var southOpaque = ly + 1 < ChunkData.Size
				? TerrainRegistry.Get(chunk.TerrainIds[CoordUtil.LocalIndex(lx, ly + 1)]).IsOpaque
				: IsChunkTerrainOpaque(southChunk!, lx, 0);
			var eastOpaque = lx + 1 < ChunkData.Size
				? TerrainRegistry.Get(chunk.TerrainIds[CoordUtil.LocalIndex(lx + 1, ly)]).IsOpaque
				: IsChunkTerrainOpaque(eastChunk!, 0, ly);
			if (topOpaque && southOpaque && eastOpaque)
			{
				occludedCellCount++;
				continue;
			}

			var drawTop = !topOpaque;
			var drawLeft = !southOpaque;
			var drawRight = !eastOpaque;
			var shadowTop = false;
			if (topOpaque && (drawLeft || drawRight))
			{
				drawTop = true;
				shadowTop = true;
			}

			if (!drawTop && !drawLeft && !drawRight)
			{
				hiddenFaceCellCount++;
				continue;
			}

			var worldX = baseX + lx;
			var worldY = baseY + ly;
			var worldZ = chunk.Coord.Cz;
			entries.Add(new TerrainSurfaceEntry(
				worldX,
				worldY,
				worldZ,
				IsoCoordUtil.WorldToScreen(worldX, worldY, worldZ),
				IsoCoordUtil.SortKey(worldX, worldY, worldZ),
				TerrainRegistry.Get(terrainId),
				drawTop,
				drawLeft,
				drawRight,
				shadowTop));
		}

		return [.. entries];
	}

	private static bool IsChunkTerrainOpaque(ChunkData chunk, int lx, int ly) =>
		TerrainRegistry.Get(chunk.TerrainIds[CoordUtil.LocalIndex(lx, ly)]).IsOpaque;

	private bool IsFullyOccluded(int wx, int wy, int wz)
	{
		var w = _state.World!;
		return w.GetTerrain(wx, wy, wz - 1).IsOpaque
			&& w.GetTerrain(wx, wy + 1, wz).IsOpaque
			&& w.GetTerrain(wx + 1, wy, wz).IsOpaque;
	}

	private static int CompareVoxelDrawCommands(VoxelDrawCommand a, VoxelDrawCommand b)
	{
		var sortCompare = IsoCoordUtil.CompareSortOrder(
			a.WorldX, a.WorldY, a.WorldZ,
			b.WorldX, b.WorldY, b.WorldZ);
		if (sortCompare != 0)
			return sortCompare;

		return 0;
	}

	// ── Drawing Methods ──

	private const float ShadowTopDarken = 0.35f;

	private void DrawBlockTop(VoxelDrawCommand cmd)
	{
		if (!_terrainAtlas.TryGetRegions(cmd.Terrain.StringId, out var regions))
			return;
		var tint = GetFaceTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ, VoxelFace.Top);
		if (cmd.ShadowTop)
			tint = new Color(tint.R * ShadowTopDarken, tint.G * ShadowTopDarken, tint.B * ShadowTopDarken, tint.A);
		tint = ApplyEditorPerspectiveAlpha(tint, cmd.WorldX, cmd.WorldY, cmd.WorldZ);
		_faceCommands.Add(new FaceSpriteCommand(
			regions.Top,
			cmd.ScreenPos,
			tint,
			cmd.SortKey));
	}

	private void DrawLeftSide(VoxelDrawCommand cmd)
	{
		if (!_terrainAtlas.TryGetRegions(cmd.Terrain.StringId, out var regions))
			return;
		var tint = ApplyEditorPerspectiveAlpha(
			GetFaceTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ, VoxelFace.Left),
			cmd.WorldX,
			cmd.WorldY,
			cmd.WorldZ);
		_faceCommands.Add(new FaceSpriteCommand(
			regions.Left,
			ResolveLeftFacePosition(cmd.ScreenPos),
			tint,
			cmd.SortKey));
	}

	private void DrawRightSide(VoxelDrawCommand cmd)
	{
		if (!_terrainAtlas.TryGetRegions(cmd.Terrain.StringId, out var regions))
			return;
		var tint = ApplyEditorPerspectiveAlpha(
			GetFaceTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ, VoxelFace.Right),
			cmd.WorldX,
			cmd.WorldY,
			cmd.WorldZ);
		_faceCommands.Add(new FaceSpriteCommand(
			regions.Right,
			ResolveRightFacePosition(cmd.ScreenPos),
			tint,
			cmd.SortKey));
	}

	private static Vector2 ResolveLeftFacePosition(Vector2 topCenter)
	{
		var x = topCenter.X - IsoCoordUtil.TileHalfW / 2f;
		var y = topCenter.Y + IsoCoordUtil.TileHalfH + (SideTextureHeight - 64) / 2f;
		return new Vector2(x, y);
	}

	private static Vector2 ResolveRightFacePosition(Vector2 topCenter)
	{
		var x = topCenter.X + IsoCoordUtil.TileHalfW / 2f;
		var y = topCenter.Y + IsoCoordUtil.TileHalfH + (SideTextureHeight - 64) / 2f;
		return new Vector2(x, y);
	}

	private Color GetVisionTint(int wx, int wy, int wz)
	{
		var band = _fogTracker.GetVisionBand(wx, wy, wz);
		return band switch
		{
			PlayerVisionBand.Focused => Colors.White,
			PlayerVisionBand.Peripheral => new Color(0.78f, 0.78f, 0.82f, 1.0f),
			PlayerVisionBand.Memory => new Color(0.42f, 0.42f, 0.48f, 0.88f),
			_ => new Color(0f, 0f, 0f, 1f),
		};
	}

	private Color GetFaceTint(int wx, int wy, int wz, VoxelFace face)
	{
		var visionTint = GetVisionTint(wx, wy, wz);
		return _lightingCalc.GetFaceTint(_state.World, wx, wy, wz, _state.PlayerZ, face, visionTint);
	}

	// ── Texture Generation ──

	/// <summary>
	/// Extract the top tile as an Image from an AtlasTexture or regular Texture2D.
	/// </summary>
	private static Image? ExtractImage(Texture2D texture)
	{
		if (texture is AtlasTexture atlas)
		{
			var fullImage = atlas.Atlas?.GetImage();
			if (fullImage == null) return null;
			var region = atlas.Region;
			return fullImage.GetRegion(new Rect2I(
				(int)region.Position.X, (int)region.Position.Y,
				(int)region.Size.X, (int)region.Size.Y));
		}
		return texture.GetImage();
	}

	// ── Entity Rendering ──

	private static readonly Vector2 DefaultEntitySpriteScale = new(0.25f, 0.25f);
	private static readonly Vector2 EntitySpriteBaseOffset = new(0f, -8f);
	private static readonly Vector2 DefaultFacilitySpriteScale = new(0.72f, 0.72f);
	private static readonly Vector2 FacilitySpriteBaseOffset = Vector2.Zero;
	private static readonly Vector2 DefaultWorldEntitySpriteScale = new(0.62f, 0.62f);
	private static readonly Vector2 WorldEntitySpriteBaseOffset = Vector2.Zero;
	private readonly Dictionary<string, ImageTexture> _entityMarkerCache = new();
	private readonly Dictionary<string, FacilityFrameBounds> _facilityFrameBoundsCache = new();

	private void CollectEntityCommands(int cx, int cy, int cz, int halfW, int halfH, int zMin, int zMax)
	{
		_entityCommands.Clear();

		if (!_editorViewActive)
		{
			foreach (var actor in _state.Actors.Values)
			{
				var visualWorld = ResolveActorVisualWorldPosition(actor);
				if (visualWorld.Z < zMin || visualWorld.Z > zMax) continue;
				if (Math.Abs(visualWorld.X - cx) > halfW || Math.Abs(visualWorld.Y - cy) > halfH) continue;
				if (_fogTracker.GetVisionBand(actor.X, actor.Y, actor.Z) == PlayerVisionBand.Unknown) continue;
				var tint = GetVisionTint(actor.X, actor.Y, actor.Z);
				var label = actor.Id == _state.PlayerId ? "P" : (actor.Faction == Factions.Hostile ? "!" : "?");
				_entityCommands.Add(new EntityDrawCommand(
					IsoCoordUtil.SortKey(actor.X, actor.Y, actor.Z),
					IsoCoordUtil.WorldToScreen(visualWorld.X, visualWorld.Y, visualWorld.Z),
					actor,
					null,
					null,
					label,
					tint));
			}
		}

		foreach (var facility in _state.Facilities.Values)
		{
			if (ShouldHidePreviewFacility(WorldToolPreviewState, facility.Id))
				continue;
			if (!TryBuildFacilityDrawCommand(facility, cx, cy, halfW, halfH, zMin, zMax, out var command))
				continue;

			_entityCommands.Add(command);
		}

		var world = _state.World!;
		var minX = cx - halfW;
		var maxX = cx + halfW;
		var minY = cy - halfH;
		var maxY = cy + halfH;

		for (var wz = zMin; wz <= zMax; wz++)
		{
			var minChunk = CoordUtil.WorldToChunk(minX, minY, wz);
			var maxChunk = CoordUtil.WorldToChunk(maxX, maxY, wz);
			for (var chunkY = minChunk.Cy; chunkY <= maxChunk.Cy; chunkY++)
			for (var chunkX = minChunk.Cx; chunkX <= maxChunk.Cx; chunkX++)
			{
				var chunk = world.Chunks.GetOrLoad(new ChunkCoord(chunkX, chunkY, wz));
				if (chunk.Entities.Count == 0)
					continue;

				foreach (var (index, entities) in chunk.Entities)
				{
					var (localX, localY) = CoordUtil.IndexToLocal(index);
					var worldX = chunk.Coord.Cx * ChunkData.Size + localX;
					var worldY = chunk.Coord.Cy * ChunkData.Size + localY;
					var worldZ = chunk.Coord.Cz;
					if (worldX < minX || worldX > maxX || worldY < minY || worldY > maxY)
						continue;
					if (_fogTracker.GetVisionBand(worldX, worldY, worldZ) == PlayerVisionBand.Unknown)
						continue;

					var tint = GetVisionTint(worldX, worldY, worldZ);
					var pos = IsoCoordUtil.WorldToScreen(worldX, worldY, worldZ);
					var key = IsoCoordUtil.SortKey(worldX, worldY, worldZ);
					for (var i = 0; i < entities.Count; i++)
					{
						var entity = entities[i];
						if (ShouldHidePreviewFixture(WorldToolPreviewState, worldX, worldY, worldZ, entity.EntityId))
							continue;

						_entityCommands.Add(new EntityDrawCommand(key, pos, null, null, entity.EntityId, entity.Glyph, tint));
					}
				}
			}
		}

		_entityCommands.Sort(static (a, b) => a.SortKey.CompareTo(b.SortKey));
	}

	private void RenderScene()
	{
		_faceCommands.Clear();

		for (var i = 0; i < _drawCommands.Count; i++)
		{
			var terrain = _drawCommands[i];
			if (terrain.DrawLeftSide) DrawLeftSide(terrain);
			if (terrain.DrawRightSide) DrawRightSide(terrain);
			if (terrain.DrawTop) DrawBlockTop(terrain);
		}

		// _drawCommands is already in stable painter order; preserve emission order so
		// same-cell faces keep a deterministic "sides first, top last" layering.
		_faceBatchCanvas?.SetCommands(_faceCommands);

		for (var i = 0; i < _entityCommands.Count; i++)
		{
			var entity = _entityCommands[i];
			if (entity.Actor != null && TryDrawActorSprite(entity.ScreenPos, entity.Actor, entity.Tint))
				continue;
			if (entity.Facility != null && TryDrawFacilitySprite(entity.ScreenPos, entity.Facility, entity.Tint))
				continue;
			if (!string.IsNullOrWhiteSpace(entity.EntityId) && TryDrawWorldEntitySprite(entity.ScreenPos, entity.EntityId, entity.Tint))
				continue;
			DrawEntityMarker(entity.ScreenPos, entity.Label, entity.Tint);
		}

		RenderHoverHighlights();
	}

	private Color ApplyEditorPerspectiveAlpha(Color tint, int worldX, int worldY, int worldZ)
	{
		if (!_editorViewActive || !_editorPerspective.ShouldFade(worldX, worldY, worldZ))
			return tint;

		return new Color(tint.R, tint.G, tint.B, tint.A * EditorPerspectiveResolver.SoftFadeAlpha);
	}

	private bool TryDrawActorSprite(Vector2 pos, Actor actor, Color tint)
	{
		if (!TryResolveActorSpriteVisual(actor, out var visual))
			return false;

		var size = visual.Region?.Size ?? visual.Texture.GetSize();
		var sprite = AcquireSprite();
		sprite.Centered = false;
		sprite.Texture = visual.Texture;
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Nearest;
		sprite.RegionEnabled = visual.Region != null;
		if (visual.Region is { } region)
			sprite.RegionRect = region;
		sprite.Scale = visual.Scale;
		sprite.Skew = 0f;
		sprite.ZIndex = 1;
		sprite.Modulate = tint;
		sprite.Position = pos + EntitySpriteBaseOffset + visual.Offset + new Vector2(
			-(size.X * visual.Scale.X) / 2f,
			-(size.Y * visual.Scale.Y));
		sprite.Visible = true;
		return true;
	}

	private bool TryDrawFacilitySprite(Vector2 pos, FacilityInstance facility, Color tint)
	{
		if (!TryResolveFacilitySpriteVisual(facility, out var visual))
			return false;

		var size = visual.Region?.Size ?? visual.Texture.GetSize();
		var sprite = AcquireSprite();
		sprite.Centered = false;
		sprite.Texture = visual.Texture;
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Nearest;
		sprite.RegionEnabled = visual.Region != null;
		if (visual.Region is { } region)
			sprite.RegionRect = region;
		sprite.Scale = visual.Scale;
		sprite.Skew = 0f;
		sprite.ZIndex = 1;
		sprite.Modulate = tint * ResolveFacilityStageTint(facility.Stage);
		sprite.Position = ResolveFacilitySpritePosition(pos, size, visual);
		sprite.Visible = true;
		return true;
	}

	private bool TryResolveActorSpriteVisual(Actor actor, out ActorSpriteVisual visual)
	{
		visual = default;
		var entry = ResolveActorRenderEntry(actor);
		if (entry == null)
			return false;

		Texture2D? texture = null;
		Rect2? region = null;
		if (IsTextureEntry(entry) && entry.TexturePath is { Length: > 0 } texturePath)
		{
			texture = ResAccess.Get<Texture2D>(texturePath);
			if (texture != null)
				region = ResolveEntitySpriteRegion(entry, actor, texture);
		}
		else if (IsSpriteSheetEntry(entry))
		{
			var sheetPath = ResolveCharacterSheetPath(entry);
			if (sheetPath.Length > 0)
			{
				texture = ResAccess.Get<Texture2D>(sheetPath);
				if (texture != null)
					region = ResolveCharacterSheetRegion(entry, actor, texture);
			}
		}

		if (texture == null)
			return false;

		visual = new ActorSpriteVisual(
			texture,
			region,
			ResolveEntitySpriteScale(entry.Scale),
			ResolveEntitySpriteOffset(entry.Offset));
		return true;
	}

	private bool TryResolveFacilitySpriteVisual(FacilityInstance facility, out FacilitySpriteVisual visual)
	{
		visual = default;
		var entry = ResolveFacilityRenderEntry(facility);
		if (entry == null || entry.TexturePath is not { Length: > 0 } texturePath)
			return false;

		var texture = ResAccess.Get<Texture2D>(texturePath);
		if (texture == null)
			return false;

		var region = ResolveFacilitySpriteRegion(entry, facility, texture);
		visual = new FacilitySpriteVisual(
			texture,
			region,
			ResolveFacilitySpriteScale(entry.Scale),
			ResolveEntitySpriteOffset(entry.Offset),
			ResolveFacilityFrameBounds(texturePath, texture, region));
		return true;
	}

	private bool TryBuildFacilityDrawCommand(
		FacilityInstance facility,
		int cx,
		int cy,
		int halfW,
		int halfH,
		int zMin,
		int zMax,
		out EntityDrawCommand command)
	{
		command = default;
		if (facility.Z < zMin || facility.Z > zMax)
			return false;

		var footprint = _state.World!.GetFootprintCells(facility);
		if (footprint.Count == 0)
			return false;

		var placement = ResolveFacilityRenderPlacement(footprint, cx, cy, halfW, halfH);
		if (!placement.Visible)
			return false;

		var def = FacilityRegistry.Get(facility.FacilityDefId);
		var label = def?.Glyph is { Length: > 0 } glyph ? glyph : "#";
		command = new EntityDrawCommand(
			placement.SortKey - 1,
			placement.ScreenPos,
			null,
			facility,
			facility.FacilityDefId,
			label,
			placement.Tint);
		return true;
	}

	private FacilityRenderPlacement ResolveFacilityRenderPlacement(
		IReadOnlyList<ZoneCell> footprint,
		int cameraX,
		int cameraY,
		int halfW,
		int halfH)
	{
		var inView = false;
		var visible = false;
		var sortKey = long.MinValue;
		var tint = Colors.White;

		for (var index = 0; index < footprint.Count; index++)
		{
			var cell = footprint[index];
			sortKey = Math.Max(sortKey, IsoCoordUtil.SortKey(cell.X, cell.Y, cell.Z));

			if (Math.Abs(cell.X - cameraX) > halfW || Math.Abs(cell.Y - cameraY) > halfH)
				continue;

			inView = true;

			if (_fogTracker.GetVisionBand(cell.X, cell.Y, cell.Z) == PlayerVisionBand.Unknown)
				continue;

			visible = true;
			tint = GetVisionTint(cell.X, cell.Y, cell.Z);
		}

		return new FacilityRenderPlacement(
			inView && visible,
			sortKey,
			ResolveFacilityFootprintScreenCenter(footprint),
			tint);
	}

	private static Vector2 ResolveFacilityFootprintScreenCenter(IReadOnlyList<ZoneCell> footprint)
	{
		if (footprint.Count == 0)
			return Vector2.Zero;

		var minX = float.MaxValue;
		var minY = float.MaxValue;
		var maxX = float.MinValue;
		var maxY = float.MinValue;
		for (var index = 0; index < footprint.Count; index++)
		{
			var cell = footprint[index];
			var screen = IsoCoordUtil.WorldToScreen(cell.X, cell.Y, cell.Z);
			minX = Math.Min(minX, screen.X);
			minY = Math.Min(minY, screen.Y);
			maxX = Math.Max(maxX, screen.X);
			maxY = Math.Max(maxY, screen.Y);
		}

		return new Vector2((minX + maxX) * 0.5f, (minY + maxY) * 0.5f);
	}

	private static Vector2 ResolveFacilitySpritePosition(Vector2 pivot, Vector2 size, FacilitySpriteVisual visual)
	{
		return ResolveFacilitySpritePosition(
			pivot,
			size,
			visual.Scale,
			visual.Offset,
			visual.FrameBounds.Bottom);
	}

	private static Vector2 ResolveFacilitySpritePosition(
		Vector2 pivot,
		Vector2 size,
		Vector2 scale,
		Vector2 offset,
		int opaqueBottom)
	{
		var bottom = opaqueBottom > 0
			? opaqueBottom * scale.Y
			: size.Y * scale.Y;
		return pivot + FacilitySpriteBaseOffset + offset + new Vector2(
			-(size.X * scale.X) / 2f,
			-bottom);
	}

	private FacilityFrameBounds ResolveFacilityFrameBounds(string texturePath, Texture2D texture, Rect2? region)
	{
		var frameRect = region is { } resolvedRegion
			? new Rect2I(
				(int)Math.Round(resolvedRegion.Position.X),
				(int)Math.Round(resolvedRegion.Position.Y),
				(int)Math.Round(resolvedRegion.Size.X),
				(int)Math.Round(resolvedRegion.Size.Y))
			: new Rect2I(0, 0, (int)texture.GetWidth(), (int)texture.GetHeight());
		var cacheKey = $"{texturePath}|{frameRect.Position.X}|{frameRect.Position.Y}|{frameRect.Size.X}|{frameRect.Size.Y}";
		if (_facilityFrameBoundsCache.TryGetValue(cacheKey, out var cached))
			return cached;

		var sourceImage = ExtractImage(texture);
		if (sourceImage == null)
			return CacheFacilityFrameBounds(cacheKey, new FacilityFrameBounds(frameRect.Size.X, frameRect.Size.Y));

		var frameImage = sourceImage.GetRegion(frameRect);
		var usedRect = frameImage.GetUsedRect();
		if (usedRect.Size.X <= 0 || usedRect.Size.Y <= 0)
			return CacheFacilityFrameBounds(cacheKey, new FacilityFrameBounds(frameRect.Size.X, frameRect.Size.Y));

		return CacheFacilityFrameBounds(
			cacheKey,
			new FacilityFrameBounds(frameRect.Size.X, usedRect.End.Y));
	}

	private FacilityFrameBounds CacheFacilityFrameBounds(string cacheKey, FacilityFrameBounds bounds)
	{
		_facilityFrameBoundsCache[cacheKey] = bounds;
		return bounds;
	}

	private bool TryDrawWorldEntitySprite(Vector2 pos, string entityId, Color tint)
	{
		if (!TryResolveWorldEntitySpriteVisual(entityId, out var visual))
			return false;

		var size = visual.Region?.Size ?? visual.Texture.GetSize();
		var sprite = AcquireSprite();
		sprite.Centered = false;
		sprite.Texture = visual.Texture;
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Nearest;
		sprite.RegionEnabled = visual.Region != null;
		if (visual.Region is { } region)
			sprite.RegionRect = region;
		sprite.Scale = visual.Scale;
		sprite.Skew = 0f;
		sprite.ZIndex = 1;
		sprite.Modulate = tint;
		sprite.Position = pos + WorldEntitySpriteBaseOffset + visual.Offset + new Vector2(
			-(size.X * visual.Scale.X) / 2f,
			-(size.Y * visual.Scale.Y));
		sprite.Visible = true;
		return true;
	}

	private bool TryResolveWorldEntitySpriteVisual(string entityId, out WorldEntitySpriteVisual visual)
	{
		visual = default;
		var entry = ResAccess.GetEntry(entityId);
		if (entry == null || !IsTextureEntry(entry) || entry.TexturePath is not { Length: > 0 } texturePath)
			return false;

		var texture = ResAccess.Get<Texture2D>(texturePath);
		if (texture == null)
			return false;

		visual = new WorldEntitySpriteVisual(
			texture,
			ResolveWorldEntitySpriteRegion(entry, texture),
			ResolveWorldEntitySpriteScale(entry.Scale),
			ResolveEntitySpriteOffset(entry.Offset));
		return true;
	}

	private static Vector2 ResolveEntitySpriteScale(float[]? scale)
	{
		if (scale is [var x, var y] && x > 0f && y > 0f)
			return new Vector2(x, y);
		return DefaultEntitySpriteScale;
	}

	private static Vector2 ResolveFacilitySpriteScale(float[]? scale)
	{
		if (scale is [var x, var y] && x > 0f && y > 0f)
			return new Vector2(x, y);
		return DefaultFacilitySpriteScale;
	}

	private static Vector2 ResolveWorldEntitySpriteScale(float[]? scale)
	{
		if (scale is [var x, var y] && x > 0f && y > 0f)
			return new Vector2(x, y);
		return DefaultWorldEntitySpriteScale;
	}

	private static Vector2 ResolveEntitySpriteOffset(float[]? offset)
	{
		if (offset is [var x, var y])
			return new Vector2(x, y);
		return Vector2.Zero;
	}

	private static Rect2? ResolveEntitySpriteRegion(ResAccess.RenderEntry entry, Actor actor, Texture2D texture)
	{
		if (!entry.UseFacing)
			return null;

		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		var frameWidth = entry.FrameWidth > 0 ? Math.Min(entry.FrameWidth, textureWidth) : textureWidth;
		var inferredFrameHeight = textureHeight % 8 == 0 ? textureHeight / 8 : textureHeight;
		var frameHeight = entry.FrameHeight > 0 ? Math.Min(entry.FrameHeight, textureHeight) : inferredFrameHeight;
		if (frameWidth <= 0 || frameHeight <= 0)
			return null;

		var rowCount = Math.Max(1, textureHeight / frameHeight);
		var row = Math.Clamp(
			DirectionalSpriteHelper.ResolveDirectionRow(actor.FacingX, actor.FacingY),
			0,
			rowCount - 1);
		return new Rect2(0, row * frameHeight, frameWidth, frameHeight);
	}

	private static Rect2? ResolveFacilitySpriteRegion(ResAccess.RenderEntry entry, FacilityInstance facility, Texture2D texture)
	{
		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		var frameWidth = entry.FrameWidth > 0 ? Math.Min(entry.FrameWidth, textureWidth) : textureWidth;
		var frameHeight = entry.FrameHeight > 0 ? Math.Min(entry.FrameHeight, textureHeight) : textureHeight;
		if (frameWidth <= 0 || frameHeight <= 0)
			return null;

		var rowCount = Math.Max(1, textureHeight / frameHeight);
		var row = Math.Clamp(ResolveFacilityRotationRow(facility.Rotation), 0, rowCount - 1);
		return new Rect2(0, row * frameHeight, frameWidth, frameHeight);
	}

	private static Rect2? ResolveWorldEntitySpriteRegion(ResAccess.RenderEntry entry, Texture2D texture)
	{
		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		if (entry.FrameWidth <= 0 || entry.FrameHeight <= 0)
			return null;

		var frameWidth = Math.Min(entry.FrameWidth, textureWidth);
		var frameHeight = Math.Min(entry.FrameHeight, textureHeight);
		if (frameWidth == textureWidth && frameHeight == textureHeight)
			return null;

		return new Rect2(0, 0, frameWidth, frameHeight);
	}

	private ResAccess.RenderEntry? ResolveActorRenderEntry(Actor actor)
	{
		if (actor.Id == _state.PlayerId)
		{
			var appearance = PlayerAppearanceCatalog.GetOrDefault(_state.PlayerAppearanceId);
			var tuning = ResAccess.GetEntry("player");
			return new ResAccess.RenderEntry
			{
				Type = "sprite_sheet",
				SheetDir = appearance.SheetDir,
				DefaultAnim = appearance.DefaultAnim,
				Scale = tuning?.Scale,
				Offset = tuning?.Offset,
				FrameWidth = tuning?.FrameWidth ?? 0,
				FrameHeight = tuning?.FrameHeight ?? 0,
				UseFacing = true,
			};
		}

		if (TryGetSupportedActorEntry(actor.Id, out var direct))
			return direct;
		if (!string.IsNullOrWhiteSpace(actor.TemplateId) && TryGetSupportedActorEntry(actor.TemplateId, out var template))
			return template;
		if (actor.Race?.Id is { Length: > 0 } raceId && TryGetSupportedActorEntry(raceId, out var race))
			return race;

		return null;
	}

	private static ResAccess.RenderEntry? ResolveFacilityRenderEntry(FacilityInstance facility)
	{
		var entry = ResAccess.GetEntry($"facility_{facility.FacilityDefId}");
		return IsTextureEntry(entry) ? entry : null;
	}

	private static bool TryGetSupportedActorEntry(string key, out ResAccess.RenderEntry? entry)
	{
		entry = ResAccess.GetEntry(key);
		return IsTextureEntry(entry) || IsSpriteSheetEntry(entry);
	}

	private static bool IsSpriteSheetEntry(ResAccess.RenderEntry? entry) =>
		entry != null
		&& string.Equals(entry.Type, "sprite_sheet", StringComparison.OrdinalIgnoreCase)
		&& !string.IsNullOrWhiteSpace(entry.SheetDir);

	private static string ResolveCharacterSheetPath(ResAccess.RenderEntry entry)
	{
		if (string.IsNullOrWhiteSpace(entry.SheetDir))
			return string.Empty;
		var animationKey = string.IsNullOrWhiteSpace(entry.DefaultAnim) ? "Idle" : entry.DefaultAnim!;
		var sheetKey = CharacterSheetMap.TryGetValue(animationKey, out var resolved) ? resolved : "Idle";
		return $"{entry.SheetDir!.TrimEnd('/')}/{sheetKey}.png";
	}

	private static Rect2? ResolveCharacterSheetRegion(ResAccess.RenderEntry entry, Actor actor, Texture2D texture)
	{
		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		var frameWidth = entry.FrameWidth > 0
			? Math.Min(entry.FrameWidth, textureWidth)
			: Math.Min(DefaultCharacterSheetFrameWidth, textureWidth);
		var frameHeight = entry.FrameHeight > 0
			? Math.Min(entry.FrameHeight, textureHeight)
			: Math.Min(DefaultCharacterSheetFrameHeight, textureHeight);
		if (frameWidth <= 0 || frameHeight <= 0)
			return null;

		var rowCount = Math.Max(1, textureHeight / frameHeight);
		var row = Math.Clamp(
			DirectionalSpriteHelper.ResolveDirectionRow(actor.FacingX, actor.FacingY),
			0,
			rowCount - 1);
		return new Rect2(0, row * frameHeight, frameWidth, frameHeight);
	}

	private static bool IsTextureEntry(ResAccess.RenderEntry? entry) =>
		entry != null
		&& string.Equals(entry.Type, "texture", StringComparison.OrdinalIgnoreCase)
		&& !string.IsNullOrWhiteSpace(entry.TexturePath);

	private static int ResolveFacilityRotationRow(FacilityRotation rotation) => rotation switch
	{
		FacilityRotation.East => 1,
		FacilityRotation.South => 2,
		FacilityRotation.West => 3,
		_ => 0,
	};

	private static Color ResolveFacilityStageTint(FacilityStage stage) => stage switch
	{
		FacilityStage.Blueprint => new Color(0.62f, 0.78f, 1.0f, 0.82f),
		FacilityStage.DeliverMaterials => new Color(0.92f, 0.86f, 0.72f, 0.94f),
		FacilityStage.Construct => new Color(0.88f, 0.80f, 0.66f, 0.97f),
		FacilityStage.Broken => new Color(0.74f, 0.70f, 0.72f, 0.94f),
		_ => Colors.White,
	};

	private void DrawEntityMarker(Vector2 pos, string label, Color tint)
	{
		var s = AcquireSprite();
		s.Centered = true;
		s.RegionEnabled = false;
		s.Scale = Vector2.One;
		s.Texture = GetEntityMarkerTexture(label);
		s.Position = pos - new Vector2(0, IsoCoordUtil.TileHalfH * 0.5f);
		s.Skew = 0f;
		s.ZIndex = 1;
		s.Modulate = tint;
		s.Visible = true;
	}

	private ImageTexture GetEntityMarkerTexture(string label)
	{
		if (_entityMarkerCache.TryGetValue(label, out var cached)) return cached;

		if (TryBuildHoverMarkerTexture(label, out var hoverTexture))
		{
			_entityMarkerCache[label] = hoverTexture;
			return hoverTexture;
		}

		const int size = 64;
		var image = Image.CreateEmpty(size, size, false, Image.Format.Rgba8);
		var center = (size - 1) * 0.5f;
		var radius = size * 0.5f - 4f;
		var color = label switch
		{
			"P" => new Color(0.2f, 0.6f, 1.0f),
			"!" => new Color(1.0f, 0.2f, 0.2f),
			"?" => new Color(0.2f, 0.8f, 0.2f),
			_ => Colors.White,
		};
		for (var py = 0; py < size; py++)
		for (var px = 0; px < size; px++)
		{
			var dx = px - center;
			var dy = py - center;
			image.SetPixel(px, py, dx * dx + dy * dy <= radius * radius ? color : Colors.Transparent);
		}
		var tex = ImageTexture.CreateFromImage(image);
		_entityMarkerCache[label] = tex;
		return tex;
	}

	// ── Sprite Pool ──

	private void BeginFrame()
	{
		_spritePool.BeginFrame();
		_spriteCount = 0;
		_faceBatchCanvas?.SetCommands(Array.Empty<FaceSpriteCommand>());
	}

	private void EndFrame()
	{
		_spritePool.EndFrame();
	}

	private Sprite2D AcquireSprite()
	{
		_spriteCount++;
		return _spritePool.Acquire(_root!);
	}

	private Vector2 ResolveRuntimeCameraTarget(int cx, int cy, int cz)
	{
		if (_runtimeViewActive && _runtimeCameraView.Mode == RuntimeCameraMode.FollowActor)
		{
			var activeActor = PartyModule.GetActiveActor(_state);
			if (activeActor != null)
			{
				var visualWorld = ResolveActorVisualWorldPosition(activeActor);
				return IsoCoordUtil.WorldToScreen(visualWorld.X, visualWorld.Y, visualWorld.Z);
			}
		}

		return _runtimeViewActive
			? _runtimeCameraView.ScreenCenterTarget
			: IsoCoordUtil.WorldToScreen(cx, cy, cz);
	}

	private void UpdateCamera(int cx, int cy, int cz)
	{
		if (_camera == null) return;
		var target = ResolveRuntimeCameraTarget(cx, cy, cz);
		if (_editorViewActive)
			_editorCameraTarget = target;
		else
			_camera.Position = target;
	}

	public void SetEditorCameraScreenTarget(Vector2 target)
	{
		_editorCameraTarget = target;
	}

	public void ClearEditorCameraSmoothing()
	{
		_editorCameraTarget = null;
	}

	// ── Types ──

	internal enum VoxelFace
	{
		Top,
		Left,
		Right,
	}

	public readonly record struct IsometricLightingSettings(
		float Ambient,
		float TopLight,
		float LeftLight,
		float RightLight,
		float DepthFalloff,
		float Contrast,
		float ShadowStrength,
		float OcclusionStep)
	{
		public IsometricLightingSettings Clamp(float minLight, float maxLight)
		{
			return new IsometricLightingSettings(
				Math.Clamp(Ambient, minLight, maxLight),
				Math.Clamp(TopLight, minLight, maxLight),
				Math.Clamp(LeftLight, minLight, maxLight),
				Math.Clamp(RightLight, minLight, maxLight),
				Math.Clamp(DepthFalloff, 0f, 0.35f),
				Math.Clamp(Contrast, 0.65f, 1.8f),
				Math.Clamp(ShadowStrength, 0f, 1.2f),
				Math.Clamp(OcclusionStep, 0f, 0.35f));
		}
	}

	private readonly record struct FaceSpriteCommand(
		Rect2 SourceRegion,
		Vector2 Position,
		Color Tint,
		long SortKey);

	private sealed partial class VoxelFaceBatchCanvas : Node2D
	{
		private FaceSpriteCommand[] _commands = Array.Empty<FaceSpriteCommand>();
		private Texture2D? _atlasTexture;

		public void SetAtlasTexture(Texture2D? atlas) => _atlasTexture = atlas;

		public void SetCommands(IReadOnlyList<FaceSpriteCommand> commands)
		{
			if (commands.Count == 0)
			{
				_commands = Array.Empty<FaceSpriteCommand>();
				QueueRedraw();
				return;
			}

			if (_commands.Length != commands.Count)
				_commands = new FaceSpriteCommand[commands.Count];

			for (var i = 0; i < commands.Count; i++)
				_commands[i] = commands[i];

			QueueRedraw();
		}

		public override void _Draw()
		{
			if (_atlasTexture == null)
				return;

			for (var i = 0; i < _commands.Length; i++)
			{
				var cmd = _commands[i];
				var size = cmd.SourceRegion.Size;
				if (size.X <= 0 || size.Y <= 0)
					continue;

				var destRect = new Rect2(cmd.Position - size / 2f, size);
				DrawTextureRectRegion(_atlasTexture, destRect, cmd.SourceRegion, cmd.Tint);
			}
		}
	}

	private struct VoxelDrawCommand
	{
		public int WorldX, WorldY, WorldZ;
		public Vector2 ScreenPos;
		public long SortKey;
		public TerrainDef Terrain;
		public bool DrawTop, DrawLeftSide, DrawRightSide;
		public bool ShadowTop;
	}

	internal readonly record struct TerrainSurfaceEntry(
		int WorldX,
		int WorldY,
		int WorldZ,
		Vector2 ScreenPos,
		long SortKey,
		TerrainDef Terrain,
		bool DrawTop,
		bool DrawLeftSide,
		bool DrawRightSide,
		bool ShadowTop);

	private readonly record struct ChunkTerrainSurfaceCache(
		int TerrainGeometryRevision,
		TerrainSurfaceEntry[] Entries,
		int EmptyCellCount,
		int OccludedCellCount,
		int HiddenFaceCellCount);

	private readonly record struct EntityDrawCommand(
		long SortKey,
		Vector2 ScreenPos,
		Actor? Actor,
		FacilityInstance? Facility,
		string? EntityId,
		string Label,
		Color Tint);

	private readonly record struct FacilityRenderPlacement(
		bool Visible,
		long SortKey,
		Vector2 ScreenPos,
		Color Tint);

	private readonly record struct ActorSpriteVisual(
		Texture2D Texture,
		Rect2? Region,
		Vector2 Scale,
		Vector2 Offset);

	private readonly record struct FacilitySpriteVisual(
		Texture2D Texture,
		Rect2? Region,
		Vector2 Scale,
		Vector2 Offset,
		FacilityFrameBounds FrameBounds);

	private readonly record struct FacilityFrameBounds(
		int Width,
		int Bottom);

	private readonly record struct WorldEntitySpriteVisual(
		Texture2D Texture,
		Rect2? Region,
		Vector2 Scale,
		Vector2 Offset);

}
