using System;
using System.Collections.Generic;
using Godot;
using MiniRPG.Core.Data;
using MiniRPG.Core.World;

namespace MiniRPG.Module.Render;

/// <summary>
/// Isometric voxel renderer: renders multi-layer block world in 2.5D isometric view.
/// Each visible block draws top face (diamond) + left side + right side.
/// Side faces are programmatically generated by sampling the bottom edges of the top tile.
/// </summary>
public class IsometricVoxelRenderer
{
	private const int DefaultViewDepthAbove = 4;
	private const int DefaultViewDepthBelow = 2;
	private const int DefaultCharacterSheetFrameWidth = 128;
	private const int DefaultCharacterSheetFrameHeight = 128;
	private const float LeftDarken = 0.65f;
	private const float RightDarken = 0.80f;
	private const int SideTextureWidth = 64;
	private const int SideTextureHeight = 160;
	private const int SideFaceHeight = 80;
	private const string VoxelTileRoot = "res://Assets/Art/Generated/voxel_tiles";

	private readonly GameState _state;
	private readonly FogOfWarTracker _fogTracker;
	private readonly int _viewW;
	private readonly int _viewH;

	private Node2D? _root;
	private Camera2D? _camera;
	private TileMapRenderModule? _parentModule;

	private readonly List<Sprite2D> _spritePool = [];
	private int _spriteCount;
	private readonly List<VoxelDrawCommand> _drawCommands = [];
	private readonly List<EntityDrawCommand> _entityCommands = [];
	private int _lastDrawCommandCount;

	private readonly Dictionary<string, CachedBlockTextures> _textureCache = new();
	private readonly Dictionary<string, Texture2D?> _voxelFaceTextureCache = new(StringComparer.OrdinalIgnoreCase);

	private static readonly Dictionary<string, Color> TerrainColors = new()
	{
		[Terrains.GrassBlock] = new Color(0.3f, 0.7f, 0.2f),
		[Terrains.Grass] = new Color(0.3f, 0.7f, 0.2f),
		[Terrains.Dirt] = new Color(0.55f, 0.35f, 0.15f),
		[Terrains.Stone] = new Color(0.5f, 0.5f, 0.5f),
		[Terrains.Sand] = new Color(0.9f, 0.85f, 0.6f),
		[Terrains.Water] = new Color(0.2f, 0.4f, 0.8f, 0.7f),
		[Terrains.Mountain] = new Color(0.4f, 0.4f, 0.45f),
		[Terrains.WallStone] = new Color(0.45f, 0.45f, 0.45f),
		[Terrains.WallSoil] = new Color(0.5f, 0.3f, 0.15f),
		[Terrains.WallGranite] = new Color(0.6f, 0.55f, 0.5f),
		[Terrains.WallObsidian] = new Color(0.15f, 0.1f, 0.2f),
		[Terrains.Tree] = new Color(0.15f, 0.5f, 0.1f),
		[Terrains.Snow] = new Color(0.95f, 0.95f, 1.0f),
		[Terrains.Ice] = new Color(0.7f, 0.85f, 1.0f, 0.8f),
		[Terrains.Lava] = new Color(1.0f, 0.3f, 0.0f),
		[Terrains.Floor] = new Color(0.6f, 0.55f, 0.45f),
		[Terrains.Rubble] = new Color(0.5f, 0.45f, 0.35f),
	};

	private static readonly Dictionary<string, string> CharacterSheetMap = new(StringComparer.OrdinalIgnoreCase)
	{
		["Idle"] = "Idle",
		["Walk"] = "Walk",
		["Run"] = "Run",
		["Attack_1"] = "Attack1",
		["Attack1"] = "Attack1",
		["Pain"] = "TakeDamage",
		["TakeDamage"] = "TakeDamage",
		["Die"] = "Die",
		["Special_1"] = "Special1",
		["Special1"] = "Special1",
	};

	public IsometricVoxelRenderer(GameState state, FogOfWarTracker fogTracker, int viewW, int viewH)
	{
		_state = state;
		_fogTracker = fogTracker;
		_viewW = viewW;
		_viewH = viewH;
	}

	public int LastSpriteCount => _spriteCount;
	public int LastDrawCommandCount => _lastDrawCommandCount;

	public void Init(Node2D root, TileSet tileSet, Camera2D? camera, TileMapRenderModule parentModule)
	{
		_root = root;
		_camera = camera;
		_parentModule = parentModule;
		_textureCache.Clear();
		_voxelFaceTextureCache.Clear();
	}

	// ── Main Render Pass ──

	public void Render()
	{
		if (_state.World == null || _root == null) return;

		BeginFrame();

		var cx = _state.PlayerX;
		var cy = _state.PlayerY;
		var cz = _state.PlayerZ;
		var halfW = _viewW / 2;
		var halfH = _viewH / 2;
		var zMin = cz - DefaultViewDepthAbove;
		var zMax = cz + DefaultViewDepthBelow;

		_drawCommands.Clear();

		for (var wy = cy - halfH; wy <= cy + halfH; wy++)
		for (var wx = cx - halfW; wx <= cx + halfW; wx++)
		for (var wz = zMax; wz >= zMin; wz--)
		{
			var terrain = _state.World.GetTerrain(wx, wy, wz);
			if (terrain.StringId == Terrains.Air || terrain.StringId == Terrains.Void)
				continue;
			if (IsFullyOccluded(wx, wy, wz))
				continue;

			var drawTop = !_state.World.GetTerrain(wx, wy, wz - 1).IsOpaque;
			var drawLeft = !_state.World.GetTerrain(wx, wy + 1, wz).IsOpaque;
			var drawRight = !_state.World.GetTerrain(wx + 1, wy, wz).IsOpaque;

			if (!drawTop && !drawLeft && !drawRight)
				continue;

			_drawCommands.Add(new VoxelDrawCommand
			{
				WorldX = wx, WorldY = wy, WorldZ = wz,
				ScreenPos = IsoCoordUtil.WorldToScreen(wx, wy, wz),
				SortKey = IsoCoordUtil.SortKey(wx, wy, wz),
				Terrain = terrain,
				DrawTop = drawTop, DrawLeftSide = drawLeft, DrawRightSide = drawRight,
			});
		}

		_drawCommands.Sort(static (a, b) => a.SortKey.CompareTo(b.SortKey));
		CollectEntityCommands(cx, cy, cz, halfW, halfH, zMin, zMax);
		_lastDrawCommandCount = _drawCommands.Count + _entityCommands.Count;
		RenderScene();
		EndFrame();
		UpdateCamera(cx, cy, cz);
	}

	private bool IsFullyOccluded(int wx, int wy, int wz)
	{
		var w = _state.World!;
		return w.GetTerrain(wx, wy, wz - 1).IsOpaque
			&& w.GetTerrain(wx, wy + 1, wz).IsOpaque
			&& w.GetTerrain(wx + 1, wy, wz).IsOpaque;
	}

	// ── Drawing Methods ──

	private void DrawBlockTop(VoxelDrawCommand cmd)
	{
		var textures = GetOrCreateTextures(cmd.Terrain);
		if (textures.Top == null) return;
		var s = AcquireSprite();
		s.Centered = true;
		s.RegionEnabled = false;
		s.Scale = Vector2.One;
		s.Texture = textures.Top;
		s.Position = cmd.ScreenPos;
		s.Skew = 0f;
		s.ZIndex = 0;
		s.Modulate = GetVisionTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ);
		s.Visible = true;
	}

	private void DrawLeftSide(VoxelDrawCommand cmd)
	{
		var textures = GetOrCreateTextures(cmd.Terrain);
		if (textures.Left == null) return;
		var s = AcquireSprite();
		s.Centered = true;
		s.RegionEnabled = false;
		s.Scale = Vector2.One;
		s.Texture = textures.Left;
		s.Position = cmd.ScreenPos + new Vector2(-IsoCoordUtil.TileHalfW / 2f, IsoCoordUtil.TileHalfH + (SideTextureHeight - 64) / 2f);
		s.Skew = 0f;
		s.ZIndex = 0;
		s.Modulate = GetVisionTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ);
		s.Visible = true;
	}

	private void DrawRightSide(VoxelDrawCommand cmd)
	{
		var textures = GetOrCreateTextures(cmd.Terrain);
		if (textures.Right == null) return;
		var s = AcquireSprite();
		s.Centered = true;
		s.RegionEnabled = false;
		s.Scale = Vector2.One;
		s.Texture = textures.Right;
		s.Position = cmd.ScreenPos + new Vector2(IsoCoordUtil.TileHalfW / 2f, IsoCoordUtil.TileHalfH + (SideTextureHeight - 64) / 2f);
		s.Skew = 0f;
		s.ZIndex = 0;
		s.Modulate = GetVisionTint(cmd.WorldX, cmd.WorldY, cmd.WorldZ);
		s.Visible = true;
	}

	private Color GetVisionTint(int wx, int wy, int wz)
	{
		var band = _fogTracker.GetVisionBand(wx, wy, wz);
		return band switch
		{
			PlayerVisionBand.Focused => Colors.White,
			PlayerVisionBand.Peripheral => new Color(0.50f, 0.50f, 0.56f),
			PlayerVisionBand.Memory => new Color(0.22f, 0.22f, 0.28f),
			_ => new Color(0f, 0f, 0f, 0f),
		};
	}

	// ── Texture Generation ──

	private CachedBlockTextures GetOrCreateTextures(TerrainDef terrain)
	{
		if (_textureCache.TryGetValue(terrain.StringId, out var cached))
			return cached;

		if (TryCreateVoxelFaceTextures(terrain, out var voxelTextures))
		{
			_textureCache[terrain.StringId] = voxelTextures;
			return voxelTextures;
		}

		// Fallback: use existing tileset extraction + procedural side generation
		Image? topImage = null;
		Texture2D? topTexture = null;

		if (_parentModule != null)
		{
			var atlasTexture = _parentModule.BuildTerrainTexture(terrain.StringId);
			if (atlasTexture != null)
			{
				topImage = ExtractImage(atlasTexture);
				if (topImage != null)
				{
					topImage = NormalizeTopImage(topImage);
					topTexture = ImageTexture.CreateFromImage(topImage);
				}
			}
		}

		if (topImage == null)
		{
			var color = TerrainColors.GetValueOrDefault(terrain.StringId, new Color(0.5f, 0.5f, 0.5f));
			topImage = CreateDiamondImage(128, 64, color);
			topTexture = ImageTexture.CreateFromImage(topImage);
		}

		var leftImage = GenerateLeftSideImage(topImage);
		var rightImage = GenerateRightSideImage(topImage);

		var result = new CachedBlockTextures(
			topTexture,
			ImageTexture.CreateFromImage(leftImage),
			ImageTexture.CreateFromImage(rightImage));

		_textureCache[terrain.StringId] = result;
		return result;
	}

	private bool TryCreateVoxelFaceTextures(TerrainDef terrain, out CachedBlockTextures textures)
	{
		textures = default;
		var topPath = ResolveVoxelTopTexturePath(terrain);
		if (string.IsNullOrWhiteSpace(topPath))
			return false;

		var topSourceTexture = GetOrLoadVoxelFaceTexture(topPath);
		if (topSourceTexture == null)
			return false;

		var topSourceImage = ExtractImage(topSourceTexture);
		if (topSourceImage == null)
			return false;

		var topDiamondImage = BuildTopDiamondFromTile(topSourceImage);
		topDiamondImage = EnhanceTopFaceEdges(topDiamondImage, terrain.Solid ? 0.48f : 0.26f);
		var topTexture = ImageTexture.CreateFromImage(topDiamondImage);

		Image sideSourceImage;
		var sidePath = ResolveVoxelSideTexturePath(terrain);
		var sideTexture = string.IsNullOrWhiteSpace(sidePath) ? null : GetOrLoadVoxelFaceTexture(sidePath);
		if (sideTexture != null)
			sideSourceImage = ExtractImage(sideTexture) ?? topSourceImage;
		else
			sideSourceImage = topSourceImage;

		var leftImage = GenerateSideFaceFromTile(sideSourceImage, isRight: false, LeftDarken);
		var rightImage = GenerateSideFaceFromTile(sideSourceImage, isRight: true, RightDarken);

		textures = new CachedBlockTextures(
			topTexture,
			ImageTexture.CreateFromImage(leftImage),
			ImageTexture.CreateFromImage(rightImage));
		return true;
	}

	private Texture2D? GetOrLoadVoxelFaceTexture(string path)
	{
		if (_voxelFaceTextureCache.TryGetValue(path, out var cached))
			return cached;

		var loaded = GD.Load<Texture2D>(path);
		_voxelFaceTextureCache[path] = loaded;
		return loaded;
	}

	private static readonly Dictionary<string, string> VoxelTileAliases = new(StringComparer.OrdinalIgnoreCase)
	{
		["grass_top"] = "tile_grass_top.png",
		["grass_side"] = "tile_grass_side.png",
		["dirt"] = "tile_dirt.png",
		["dirt_side"] = "tile_dirt.png",
		["soil"] = "tile_dirt.png",
		["soil_side"] = "tile_dirt.png",
		["stone"] = "tile_stone.png",
		["stone_side"] = "tile_stone.png",
		["sand"] = "tile_sand.png",
		["sand_side"] = "tile_sand.png",
		["gravel"] = "tile_gravel.png",
		["gravel_side"] = "tile_gravel.png",
		["mud"] = "tile_mud.png",
		["mud_side"] = "tile_mud.png",
		["clay"] = "tile_clay.png",
		["clay_side"] = "tile_clay.png",
		["snow"] = "tile_snow.png",
		["snow_side"] = "tile_snow.png",
		["ash"] = "tile_ash.png",
		["ash_side"] = "tile_ash.png",
		["plank"] = "tile_plank.png",
		["plank_side"] = "tile_plank.png",
		["log_top"] = "tile_log_top.png",
		["log_side"] = "tile_log_side.png",
		["brick"] = "tile_brick.png",
		["brick_side"] = "tile_brick.png",
		["brick_mossy"] = "tile_brick_mossy.png",
		["brick_mossy_side"] = "tile_brick_mossy.png",
		["brick_cracked"] = "tile_brick_cracked.png",
		["brick_cracked_side"] = "tile_brick_cracked.png",
		["ore_coal"] = "ores/tile_stone_ore_coal.png",
		["ore_iron"] = "ores/tile_stone_ore_iron.png",
		["ore_copper"] = "ores/tile_stone_ore_copper.png",
		["ore_gold"] = "ores/tile_stone_ore_gold.png",
		["ore_crystal"] = "ores/tile_stone_ore_crystal.png",
		["wall_stone_side"] = "tile_stone.png",
		["wall_granite_side"] = "tile_stone.png",
		["wall_obsidian_side"] = "tile_stone.png",
		["wall_iron_side"] = "tile_stone.png",
		["mountain_side"] = "tile_stone.png",
		["rubble"] = "tile_gravel.png",
		["rubble_side"] = "tile_gravel.png",
	};

	private static string ResolveVoxelTopTexturePath(TerrainDef terrain)
	{
		var token = string.IsNullOrWhiteSpace(terrain.TopTile) ? terrain.StringId : terrain.TopTile;
		var fileName = ResolveVoxelFileName(token, isTop: true);
		return string.IsNullOrWhiteSpace(fileName) ? string.Empty : $"{VoxelTileRoot}/{fileName}";
	}

	private static string ResolveVoxelSideTexturePath(TerrainDef terrain)
	{
		var token = string.IsNullOrWhiteSpace(terrain.SideTile) ? terrain.StringId : terrain.SideTile;
		var fileName = ResolveVoxelFileName(token, isTop: false);
		return string.IsNullOrWhiteSpace(fileName) ? string.Empty : $"{VoxelTileRoot}/{fileName}";
	}

	private static string ResolveVoxelFileName(string token, bool isTop)
	{
		if (VoxelTileAliases.TryGetValue(token, out var alias))
			return alias;

		var inferred = token switch
		{
			"grass_block" => isTop ? "tile_grass_top.png" : "tile_grass_side.png",
			"grass" => isTop ? "tile_grass_top.png" : "tile_grass_side.png",
			"tree" => "tile_grass_side.png",
			"fungus" => "tile_grass_side.png",
			"dirt" => "tile_dirt.png",
			"swamp" => "tile_dirt.png",
			"marsh" => "tile_dirt.png",
			"sand" => "tile_dirt.png",
			"wall_soil" => "tile_dirt.png",
			"stone" => "tile_stone.png",
			"gravel" => "tile_stone.png",
			"mountain" => "tile_stone.png",
			"rubble" => "tile_stone.png",
			"floor" => "tile_stone.png",
			"wall_stone" => "tile_stone.png",
			"wall_granite" => "tile_stone.png",
			"wall_obsidian" => "tile_stone.png",
			"wall_iron" => "tile_stone.png",
			"crystal_vein" => "tile_stone.png",
			_ => string.Empty,
		};

		return inferred;
	}

	private static Image BuildTopDiamondFromTile(Image tileImage)
	{
		const int targetW = 128;
		const int targetH = 64;
		var result = Image.CreateEmpty(targetW, targetH, false, Image.Format.Rgba8);
		var srcW = tileImage.GetWidth();
		var srcH = tileImage.GetHeight();
		var halfW = targetW / 2f;
		var halfH = targetH / 2f;

		for (var y = 0; y < targetH; y++)
		{
			for (var x = 0; x < targetW; x++)
			{
				var nx = (x - halfW) / halfW;
				var ny = (y - halfH) / halfH;
				if (Math.Abs(nx) + Math.Abs(ny) > 1f)
				{
					result.SetPixel(x, y, Colors.Transparent);
					continue;
				}

				var u = (nx - ny + 1f) * 0.5f;
				var v = (nx + ny + 1f) * 0.5f;
				var sx = Math.Clamp((int)Math.Round(u * (srcW - 1)), 0, srcW - 1);
				var sy = Math.Clamp((int)Math.Round(v * (srcH - 1)), 0, srcH - 1);
				result.SetPixel(x, y, tileImage.GetPixel(sx, sy));
			}
		}

		return result;
	}

	private static Image EnhanceTopFaceEdges(Image diamond, float outlineStrength)
	{
		var width = diamond.GetWidth();
		var height = diamond.GetHeight();
		var outlined = diamond.Duplicate();
		outlineStrength = Math.Clamp(outlineStrength, 0f, 0.75f);

		for (var y = 1; y < height - 1; y++)
		for (var x = 1; x < width - 1; x++)
		{
			var c = diamond.GetPixel(x, y);
			if (c.A <= 0.01f)
				continue;

			var isEdge = diamond.GetPixel(x - 1, y).A <= 0.01f
				|| diamond.GetPixel(x + 1, y).A <= 0.01f
				|| diamond.GetPixel(x, y - 1).A <= 0.01f
				|| diamond.GetPixel(x, y + 1).A <= 0.01f;
			if (!isEdge)
				continue;

			var factor = 1f - outlineStrength;
			outlined.SetPixel(x, y, new Color(c.R * factor, c.G * factor, c.B * factor, c.A));
		}

		return outlined;
	}

	private static Image GenerateSideFaceFromTile(Image tileImage, bool isRight, float darken)
	{
		var iw = SideTextureWidth;
		var ih = SideTextureHeight;
		var faceH = SideFaceHeight;
		var img = Image.CreateEmpty(iw, ih, false, Image.Format.Rgba8);
		var tw = tileImage.GetWidth();
		var th = tileImage.GetHeight();

		for (var px = 0; px < iw; px++)
		{
			var t = px / (float)(iw - 1);
			var sampleX = isRight
				? (tw - 1) - (int)Math.Round(t * (tw - 1))
				: (int)Math.Round(t * (tw - 1));
			var pyStart = isRight
				? (int)((iw - 1 - px) * 0.5f)
				: (int)(px * 0.5f);

			for (var dy = 0; dy < faceH; dy++)
			{
				var py = pyStart + dy;
				if (py >= ih) break;

				var sampleY = Math.Clamp((int)Math.Round(((dy + (th - faceH)) / (float)(th - 1)) * (th - 1)), 0, th - 1);
				var color = SampleArea(tileImage, sampleX, sampleY, tw, th);
				var gradient = 1.0f - (dy / (float)faceH) * 0.17f;
				var c = color * new Color(darken * gradient, darken * gradient, darken * gradient, 1f);
				c.A = color.A;
				img.SetPixel(px, py, c);
			}
		}

		return img;
	}

	/// <summary>
	/// Extract the top tile as an Image from an AtlasTexture or regular Texture2D.
	/// </summary>
	private static Image? ExtractImage(Texture2D texture)
	{
		if (texture is AtlasTexture atlas)
		{
			var fullImage = atlas.Atlas?.GetImage();
			if (fullImage == null) return null;
			var region = atlas.Region;
			return fullImage.GetRegion(new Rect2I(
				(int)region.Position.X, (int)region.Position.Y,
				(int)region.Size.X, (int)region.Size.Y));
		}
		return texture.GetImage();
	}

	/// <summary>
	/// Terrain atlas entries are packed isometric blocks, not pure top-face diamonds.
	/// Extract the visible top cap and mirror it into a standalone 128x64 diamond so
	/// procedural side generation does not sample the baked wall pixels.
	/// </summary>
	private static Image NormalizeTopImage(Image sourceImage)
	{
		if (!TryExtractTopDiamondFromPackedTile(sourceImage, out var normalized) || normalized == null)
			return sourceImage;
		return normalized;
	}

	private static bool TryExtractTopDiamondFromPackedTile(Image sourceImage, out Image? normalized)
	{
		normalized = null;
		var width = sourceImage.GetWidth();
		var height = sourceImage.GetHeight();
		var minX = width;
		var minY = height;
		var maxX = -1;
		var maxY = -1;
		var rowWidths = new int[height];

		for (var y = 0; y < height; y++)
		{
			var rowMinX = width;
			var rowMaxX = -1;
			for (var x = 0; x < width; x++)
			{
				if (sourceImage.GetPixel(x, y).A <= 0.01f)
					continue;

				rowMinX = Math.Min(rowMinX, x);
				rowMaxX = Math.Max(rowMaxX, x);
			}

			if (rowMaxX < 0)
				continue;

			rowWidths[y] = rowMaxX - rowMinX + 1;
			minX = Math.Min(minX, rowMinX);
			minY = Math.Min(minY, y);
			maxX = Math.Max(maxX, rowMaxX);
			maxY = Math.Max(maxY, y);
		}

		if (maxX < minX || maxY < minY)
			return false;

		if (!TryResolvePackedTileTopCap(rowWidths, minY, maxY, out var maxRowWidth, out var seamY, out _))
			return false;

		var targetWidth = (int)(IsoCoordUtil.TileHalfW * 2f);
		var targetHalfHeight = (int)IsoCoordUtil.TileHalfH;
		if (targetWidth <= 0 || targetHalfHeight <= 0)
			return false;

		var capHeight = seamY - minY + 1;
		var cap = sourceImage.GetRegion(new Rect2I(minX, minY, maxRowWidth, capHeight));
		cap.Resize(targetWidth, targetHalfHeight);

		var diamond = Image.CreateEmpty(targetWidth, targetHalfHeight * 2, false, Image.Format.Rgba8);
		for (var y = 0; y < targetHalfHeight; y++)
		{
			for (var x = 0; x < targetWidth; x++)
			{
				var pixel = cap.GetPixel(x, y);
				diamond.SetPixel(x, y, pixel);
				diamond.SetPixel(x, (targetHalfHeight * 2) - 1 - y, pixel);
			}
		}

		normalized = diamond;
		return true;
	}

	private static bool TryResolvePackedTileTopCap(int[] rowWidths, int minY, int maxY, out int maxRowWidth, out int seamY, out int plateauRows)
	{
		maxRowWidth = 0;
		seamY = -1;
		plateauRows = 0;
		if (rowWidths.Length == 0 || minY < 0 || maxY >= rowWidths.Length || minY >= maxY)
			return false;

		for (var y = minY; y <= maxY; y++)
			maxRowWidth = Math.Max(maxRowWidth, rowWidths[y]);

		if (maxRowWidth < 16)
			return false;

		for (var y = minY; y <= maxY; y++)
		{
			if (rowWidths[y] < maxRowWidth - 1)
			{
				if (seamY >= 0)
					break;
				continue;
			}

			if (seamY < 0)
				seamY = y;
			plateauRows++;
		}

		var capHeight = seamY - minY + 1;
		return seamY > minY && plateauRows >= 4 && capHeight >= 8;
	}

	/// <summary>
	/// Generate left side face as a 64x64 parallelogram image.
	/// The parallelogram covers the area below the diamond's bottom-left edge:
	///   TL=(0,0) TR=(63,31) BR=(63,63) BL=(0,32)  (in image coords)
	/// Colors are sampled from the left-bottom edge of the top diamond, darkened by LeftDarken.
	/// </summary>
	private static Image GenerateLeftSideImage(Image topImage)
	{
		const int iw = 64;
		const int ih = 64;
		const int faceH = 32;
		var img = Image.CreateEmpty(iw, ih, false, Image.Format.Rgba8);
		var tw = topImage.GetWidth();
		var th = topImage.GetHeight();
		var halfW = tw / 2;
		var halfH = th / 2;

		for (var px = 0; px < iw; px++)
		{
			var t = px / (float)(iw - 1);
			var sampleX = (int)(t * halfW);
			var sampleY = halfH + (int)(t * (halfH - 1));
			sampleX = Math.Clamp(sampleX, 0, tw - 1);
			sampleY = Math.Clamp(sampleY, 0, th - 1);
			var color = SampleArea(topImage, sampleX, sampleY, tw, th);

			var pyStart = (int)(px * 0.5f);
			for (var dy = 0; dy < faceH; dy++)
			{
				var py = pyStart + dy;
				if (py >= ih) break;
				var gradientFactor = 1.0f - (dy / (float)faceH) * 0.2f;
				var c = color * new Color(LeftDarken * gradientFactor, LeftDarken * gradientFactor, LeftDarken * gradientFactor, 1f);
				c.A = color.A;
				img.SetPixel(px, py, c);
			}
		}
		return img;
	}

	/// <summary>
	/// Generate right side face as a 64x64 parallelogram image.
	/// The parallelogram covers the area below the diamond's bottom-right edge:
	///   TL=(0,32) TR=(63,0) BR=(63,32) BL=(0,64)  (in image coords)
	/// Colors are sampled from the right-bottom edge of the top diamond, darkened by RightDarken.
	/// </summary>
	private static Image GenerateRightSideImage(Image topImage)
	{
		const int iw = 64;
		const int ih = 64;
		const int faceH = 32;
		var img = Image.CreateEmpty(iw, ih, false, Image.Format.Rgba8);
		var tw = topImage.GetWidth();
		var th = topImage.GetHeight();
		var halfW = tw / 2;
		var halfH = th / 2;

		for (var px = 0; px < iw; px++)
		{
			var t = px / (float)(iw - 1);
			var sampleX = halfW + (int)(t * (halfW - 1));
			var sampleY = (th - 1) - (int)(t * (halfH - 1));
			sampleX = Math.Clamp(sampleX, 0, tw - 1);
			sampleY = Math.Clamp(sampleY, 0, th - 1);
			var color = SampleArea(topImage, sampleX, sampleY, tw, th);

			var pyStart = (int)((iw - 1 - px) * 0.5f);
			for (var dy = 0; dy < faceH; dy++)
			{
				var py = pyStart + dy;
				if (py >= ih) break;
				var gradientFactor = 1.0f - (dy / (float)faceH) * 0.2f;
				var c = color * new Color(RightDarken * gradientFactor, RightDarken * gradientFactor, RightDarken * gradientFactor, 1f);
				c.A = color.A;
				img.SetPixel(px, py, c);
			}
		}
		return img;
	}

	/// <summary>Sample a 3x3 area around (cx,cy) and return the average color.</summary>
	private static Color SampleArea(Image img, int cx, int cy, int w, int h)
	{
		float r = 0, g = 0, b = 0, a = 0;
		var count = 0;
		for (var dy = -1; dy <= 1; dy++)
		for (var dx = -1; dx <= 1; dx++)
		{
			var sx = Math.Clamp(cx + dx, 0, w - 1);
			var sy = Math.Clamp(cy + dy, 0, h - 1);
			var c = img.GetPixel(sx, sy);
			if (c.A < 0.01f) continue; // skip transparent pixels
			r += c.R; g += c.G; b += c.B; a += c.A;
			count++;
		}
		if (count == 0) return new Color(0.5f, 0.5f, 0.5f);
		return new Color(r / count, g / count, b / count, a / count);
	}

	/// <summary>Create a solid-color diamond image (fallback when no atlas tile available).</summary>
	private static Image CreateDiamondImage(int w, int h, Color color)
	{
		var image = Image.CreateEmpty(w, h, false, Image.Format.Rgba8);
		var halfW = w / 2;
		var halfH = h / 2;
		for (var py = 0; py < h; py++)
		for (var px = 0; px < w; px++)
		{
			var dx = Math.Abs(px - halfW) / (float)halfW;
			var dy = Math.Abs(py - halfH) / (float)halfH;
			image.SetPixel(px, py, dx + dy <= 1.0f ? color : Colors.Transparent);
		}
		return image;
	}

	// ── Entity Rendering ──

	private static readonly Vector2 DefaultEntitySpriteScale = new(0.25f, 0.25f);
	private static readonly Vector2 EntitySpriteBaseOffset = new(0f, -8f);
	private readonly Dictionary<string, ImageTexture> _entityMarkerCache = new();

	private void CollectEntityCommands(int cx, int cy, int cz, int halfW, int halfH, int zMin, int zMax)
	{
		_entityCommands.Clear();

		foreach (var actor in _state.Actors.Values)
		{
			if (actor.Z < zMin || actor.Z > zMax) continue;
			if (Math.Abs(actor.X - cx) > halfW || Math.Abs(actor.Y - cy) > halfH) continue;
			var tint = GetVisionTint(actor.X, actor.Y, actor.Z);
			if (tint.A <= 0f) continue;
			var label = actor.Id == _state.PlayerId ? "P" : (actor.Faction == Factions.Hostile ? "!" : "?");
			_entityCommands.Add(new EntityDrawCommand(
				IsoCoordUtil.SortKey(actor.X, actor.Y, actor.Z),
				IsoCoordUtil.WorldToScreen(actor.X, actor.Y, actor.Z),
				actor,
				label,
				tint));
		}

		for (var wy = cy - halfH; wy <= cy + halfH; wy++)
		for (var wx = cx - halfW; wx <= cx + halfW; wx++)
		for (var wz = zMax; wz >= zMin; wz--)
		{
			var entities = _state.World!.GetEntities(wx, wy, wz);
			if (entities.Count == 0) continue;
			var tint = GetVisionTint(wx, wy, wz);
			if (tint.A <= 0f) continue;
			var pos = IsoCoordUtil.WorldToScreen(wx, wy, wz);
			var key = IsoCoordUtil.SortKey(wx, wy, wz);
			foreach (var e in entities)
				_entityCommands.Add(new EntityDrawCommand(key, pos, null, e.Glyph, tint));
		}

		_entityCommands.Sort(static (a, b) => a.SortKey.CompareTo(b.SortKey));
	}

	private void RenderScene()
	{
		var terrainIndex = 0;
		var entityIndex = 0;
		while (terrainIndex < _drawCommands.Count || entityIndex < _entityCommands.Count)
		{
			if (entityIndex >= _entityCommands.Count
				|| (terrainIndex < _drawCommands.Count && _drawCommands[terrainIndex].SortKey <= _entityCommands[entityIndex].SortKey))
			{
				var terrain = _drawCommands[terrainIndex++];
				if (terrain.DrawTop) DrawBlockTop(terrain);
				if (terrain.DrawLeftSide) DrawLeftSide(terrain);
				if (terrain.DrawRightSide) DrawRightSide(terrain);
				continue;
			}

			var entity = _entityCommands[entityIndex++];
			if (entity.Actor != null && TryDrawActorSprite(entity.ScreenPos, entity.Actor, entity.Tint))
				continue;
			DrawEntityMarker(entity.ScreenPos, entity.Label, entity.Tint);
		}
	}

	private bool TryDrawActorSprite(Vector2 pos, Actor actor, Color tint)
	{
		if (!TryResolveActorSpriteVisual(actor, out var visual))
			return false;

		var size = visual.Region?.Size ?? visual.Texture.GetSize();
		var sprite = AcquireSprite();
		sprite.Centered = false;
		sprite.Texture = visual.Texture;
		sprite.TextureFilter = CanvasItem.TextureFilterEnum.Nearest;
		sprite.RegionEnabled = visual.Region != null;
		if (visual.Region is { } region)
			sprite.RegionRect = region;
		sprite.Scale = visual.Scale;
		sprite.Skew = 0f;
		sprite.ZIndex = 1;
		sprite.Modulate = tint;
		sprite.Position = pos + EntitySpriteBaseOffset + visual.Offset + new Vector2(
			-(size.X * visual.Scale.X) / 2f,
			-(size.Y * visual.Scale.Y));
		sprite.Visible = true;
		return true;
	}

	private bool TryResolveActorSpriteVisual(Actor actor, out ActorSpriteVisual visual)
	{
		visual = default;
		var entry = ResolveActorRenderEntry(actor);
		if (entry == null)
			return false;

		Texture2D? texture = null;
		Rect2? region = null;
		if (IsTextureEntry(entry) && entry.TexturePath is { Length: > 0 } texturePath)
		{
			texture = ResAccess.Get<Texture2D>(texturePath);
			if (texture != null)
				region = ResolveEntitySpriteRegion(entry, actor, texture);
		}
		else if (IsSpriteSheetEntry(entry))
		{
			var sheetPath = ResolveCharacterSheetPath(entry);
			if (sheetPath.Length > 0)
			{
				texture = ResAccess.Get<Texture2D>(sheetPath);
				if (texture != null)
					region = ResolveCharacterSheetRegion(entry, actor, texture);
			}
		}

		if (texture == null)
			return false;

		visual = new ActorSpriteVisual(
			texture,
			region,
			ResolveEntitySpriteScale(entry.Scale),
			ResolveEntitySpriteOffset(entry.Offset));
		return true;
	}

	private static Vector2 ResolveEntitySpriteScale(float[]? scale)
	{
		if (scale is [var x, var y] && x > 0f && y > 0f)
			return new Vector2(x, y);
		return DefaultEntitySpriteScale;
	}

	private static Vector2 ResolveEntitySpriteOffset(float[]? offset)
	{
		if (offset is [var x, var y])
			return new Vector2(x, y);
		return Vector2.Zero;
	}

	private static Rect2? ResolveEntitySpriteRegion(ResAccess.RenderEntry entry, Actor actor, Texture2D texture)
	{
		if (!entry.UseFacing)
			return null;

		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		var frameWidth = entry.FrameWidth > 0 ? Math.Min(entry.FrameWidth, textureWidth) : textureWidth;
		var inferredFrameHeight = textureHeight % 8 == 0 ? textureHeight / 8 : textureHeight;
		var frameHeight = entry.FrameHeight > 0 ? Math.Min(entry.FrameHeight, textureHeight) : inferredFrameHeight;
		if (frameWidth <= 0 || frameHeight <= 0)
			return null;

		var rowCount = Math.Max(1, textureHeight / frameHeight);
		var row = Math.Clamp(
			DirectionalSpriteHelper.ResolveDirectionRow(actor.FacingX, actor.FacingY),
			0,
			rowCount - 1);
		return new Rect2(0, row * frameHeight, frameWidth, frameHeight);
	}

	private ResAccess.RenderEntry? ResolveActorRenderEntry(Actor actor)
	{
		if (actor.Id == _state.PlayerId)
		{
			var appearance = PlayerAppearanceCatalog.GetOrDefault(_state.PlayerAppearanceId);
			var tuning = ResAccess.GetEntry("player");
			return new ResAccess.RenderEntry
			{
				Type = "sprite_sheet",
				SheetDir = appearance.SheetDir,
				DefaultAnim = appearance.DefaultAnim,
				Scale = tuning?.Scale,
				Offset = tuning?.Offset,
				FrameWidth = tuning?.FrameWidth ?? 0,
				FrameHeight = tuning?.FrameHeight ?? 0,
				UseFacing = true,
			};
		}

		if (TryGetSupportedActorEntry(actor.Id, out var direct))
			return direct;
		if (!string.IsNullOrWhiteSpace(actor.TemplateId) && TryGetSupportedActorEntry(actor.TemplateId, out var template))
			return template;
		if (actor.Race?.Id is { Length: > 0 } raceId && TryGetSupportedActorEntry(raceId, out var race))
			return race;

		return null;
	}

	private static bool TryGetSupportedActorEntry(string key, out ResAccess.RenderEntry? entry)
	{
		entry = ResAccess.GetEntry(key);
		return IsTextureEntry(entry) || IsSpriteSheetEntry(entry);
	}

	private static bool IsSpriteSheetEntry(ResAccess.RenderEntry? entry) =>
		entry != null
		&& string.Equals(entry.Type, "sprite_sheet", StringComparison.OrdinalIgnoreCase)
		&& !string.IsNullOrWhiteSpace(entry.SheetDir);

	private static string ResolveCharacterSheetPath(ResAccess.RenderEntry entry)
	{
		if (string.IsNullOrWhiteSpace(entry.SheetDir))
			return string.Empty;
		var animationKey = string.IsNullOrWhiteSpace(entry.DefaultAnim) ? "Idle" : entry.DefaultAnim!;
		var sheetKey = CharacterSheetMap.TryGetValue(animationKey, out var resolved) ? resolved : "Idle";
		return $"{entry.SheetDir!.TrimEnd('/')}/{sheetKey}.png";
	}

	private static Rect2? ResolveCharacterSheetRegion(ResAccess.RenderEntry entry, Actor actor, Texture2D texture)
	{
		var textureWidth = (int)texture.GetWidth();
		var textureHeight = (int)texture.GetHeight();
		if (textureWidth <= 0 || textureHeight <= 0)
			return null;

		var frameWidth = entry.FrameWidth > 0
			? Math.Min(entry.FrameWidth, textureWidth)
			: Math.Min(DefaultCharacterSheetFrameWidth, textureWidth);
		var frameHeight = entry.FrameHeight > 0
			? Math.Min(entry.FrameHeight, textureHeight)
			: Math.Min(DefaultCharacterSheetFrameHeight, textureHeight);
		if (frameWidth <= 0 || frameHeight <= 0)
			return null;

		var rowCount = Math.Max(1, textureHeight / frameHeight);
		var row = Math.Clamp(
			DirectionalSpriteHelper.ResolveDirectionRow(actor.FacingX, actor.FacingY),
			0,
			rowCount - 1);
		return new Rect2(0, row * frameHeight, frameWidth, frameHeight);
	}

	private static bool IsTextureEntry(ResAccess.RenderEntry? entry) =>
		entry != null
		&& string.Equals(entry.Type, "texture", StringComparison.OrdinalIgnoreCase)
		&& !string.IsNullOrWhiteSpace(entry.TexturePath);

	private void DrawEntityMarker(Vector2 pos, string label, Color tint)
	{
		var s = AcquireSprite();
		s.Centered = true;
		s.RegionEnabled = false;
		s.Scale = Vector2.One;
		s.Texture = GetEntityMarkerTexture(label);
		s.Position = pos - new Vector2(0, IsoCoordUtil.TileHalfH * 0.5f);
		s.Skew = 0f;
		s.ZIndex = 1;
		s.Modulate = tint;
		s.Visible = true;
	}

	private ImageTexture GetEntityMarkerTexture(string label)
	{
		if (_entityMarkerCache.TryGetValue(label, out var cached)) return cached;
		const int size = 32;
		var image = Image.CreateEmpty(size, size, false, Image.Format.Rgba8);
		var center = size / 2f;
		var radius = size / 2f - 2f;
		var color = label switch
		{
			"P" => new Color(0.2f, 0.6f, 1.0f),
			"!" => new Color(1.0f, 0.2f, 0.2f),
			"?" => new Color(0.2f, 0.8f, 0.2f),
			_ => new Color(0.8f, 0.8f, 0.8f),
		};
		for (var py = 0; py < size; py++)
		for (var px = 0; px < size; px++)
		{
			var dx = px - center;
			var dy = py - center;
			image.SetPixel(px, py, dx * dx + dy * dy <= radius * radius ? color : Colors.Transparent);
		}
		var tex = ImageTexture.CreateFromImage(image);
		_entityMarkerCache[label] = tex;
		return tex;
	}

	// ── Sprite Pool ──

	private void BeginFrame() { _spriteCount = 0; }

	private void EndFrame()
	{
		for (var i = _spriteCount; i < _spritePool.Count; i++)
			_spritePool[i].Visible = false;
	}

	private Sprite2D AcquireSprite()
	{
		var idx = _spriteCount++;
		if (idx < _spritePool.Count) return _spritePool[idx];
		var sprite = new Sprite2D
		{
			Name = "VoxelSprite" + _spritePool.Count.ToString(),
			Centered = true,
			TextureFilter = CanvasItem.TextureFilterEnum.Nearest,
		};
		_root!.AddChild(sprite);
		_spritePool.Add(sprite);
		return sprite;
	}

	private void UpdateCamera(int cx, int cy, int cz)
	{
		if (_camera != null)
			_camera.Position = IsoCoordUtil.WorldToScreen(cx, cy, cz);
	}

	// ── Types ──

	private struct VoxelDrawCommand
	{
		public int WorldX, WorldY, WorldZ;
		public Vector2 ScreenPos;
		public long SortKey;
		public TerrainDef Terrain;
		public bool DrawTop, DrawLeftSide, DrawRightSide;
	}

	private readonly record struct EntityDrawCommand(
		long SortKey,
		Vector2 ScreenPos,
		Actor? Actor,
		string Label,
		Color Tint);

	private readonly record struct ActorSpriteVisual(
		Texture2D Texture,
		Rect2? Region,
		Vector2 Scale,
		Vector2 Offset);

	private record struct CachedBlockTextures(Texture2D? Top, Texture2D? Left, Texture2D? Right);
}
