<Project Sdk="Godot.NET.Sdk/4.6.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>MiniRPG</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GodotProjectDir Condition="'$(GodotProjectDir)' == ''">$(MSBuildProjectDirectory)\..</GodotProjectDir>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="GodotProjectDir" />
    <Compile Include="..\AssemblyInfo.cs" Link="AssemblyInfo.cs" />
    <Compile Include="..\App\GlobalUsings.cs" Link="GlobalUsings.cs" />
    <Compile Include="..\Core\**\*.cs" />
    <Compile Include="..\Module\**\*.cs" />
    <Compile Include="..\Artifacts\enet-csharp-vendor\enet-csharp\ENet\**\*.cs" Link="Vendor\ENet\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Remove="..\Core\**\*.uid" />
    <Compile Remove="..\Module\**\*.uid" />
  </ItemGroup>
</Project>
